# Generates lib/l10n/app_{en,hi,te}.arb from one table so the three stay in
# sync. Run: python tool/gen_arb.py   (then `flutter gen-l10n` or `flutter pub get`)
#
# Keys listed in MED contain medical/clinical terminology. Their Hindi/Telugu
# strings carry a "GLOSSARY-REVIEW" description in the ARB and MUST be
# reviewed against the clinician-approved glossary before production
# (docs/product/11_DESIGN_SYSTEM.md, Localization). Drug names, units and
# vital abbreviations stay in English on purpose.
import json
import os

T = []  # (key, en, hi, te)


def k(key, en, hi, te):
    T.append((key, en, hi, te))


# Placeholders: key -> {name: type}
P = {
    'ageYears': {'age': 'int'}, 'daysCount': {'count': 'int'}, 'dietMealsCount': {'count': 'int'},
    'dietValidWeeks': {'weeks': 'int'}, 'earnServices': {'count': 'int'}, 'helloDoctor': {'name': 'String'},
    'leaveConflictsTitle': {'count': 'int'}, 'loginDevOtpHint': {'code': 'String'}, 'loginOtpSentTo': {'phone': 'String'},
    'mfaWrongCodeAttempts': {'count': 'int'}, 'pageOf': {'page': 'int', 'total': 'int'}, 'pdfDocument': {'title': 'String'},
    'ratingLine': {'rating': 'String', 'count': 'int'}, 'readingsCount': {'count': 'int'}, 'regNo': {'number': 'String'},
    'rxFor': {'name': 'String'}, 'rxOverrideReasonHint': {'min': 'int'}, 'rxPack': {'pack': 'String'},
    'rxPdfTitle': {'name': 'String'}, 'scheduleHint': {'days': 'int'}, 'slotMinutes': {'minutes': 'int'},
    'soDue': {'date': 'String'}, 'unreadCount': {'count': 'int'}, 'updateVersions': {'current': 'String', 'minimum': 'String'},
    'videoOpensAt': {'time': 'String'}, 'vitalRange': {'min': 'String', 'max': 'String'},
    'vitalTrendSemantics': {'vital': 'String', 'min': 'String', 'max': 'String', 'count': 'int'},
}

MED = {
    'activeMedsTitle', 'allergiesNone', 'allergiesTitle', 'conditionsTitle', 'intakeComplaint', 'intakeSeverity',
    'intakeSymptoms', 'recentVitalsTitle', 'rxAcknowledge', 'rxDose', 'rxFrequency', 'rxMajorBlocked', 'rxNoWarnings',
    'sevMajor', 'sevModerate', 'warnAllergy', 'warnDuplicate', 'warnInteraction', 'warnDoseForm', 'vitalBpSystolic',
    'vitalBpDiastolic', 'vitalPulse', 'vitalSpo2', 'vitalTemperature', 'vitalGlucose', 'vitalRespiratoryRate',
    'soapS', 'soapO', 'soapA', 'soapP', 'formTablet', 'formCapsule', 'formSyrup', 'formInjection', 'formOintment',
    'formDrops', 'formInhaler', 'emergencyNotice', 'homeVisitFindingsTitle', 'rxDuration',
}

# ------------------------------------------------------------------ General
k('appTitle', 'CareCompanion Doctor', 'केयरकम्पैनियन डॉक्टर', 'కేర్‌కంపానియన్ డాక్టర్')
k('commonLoading', 'Loading', 'लोड हो रहा है', 'లోడ్ అవుతోంది')
k('commonRetry', 'Retry', 'फिर से कोशिश करें', 'మళ్లీ ప్రయత్నించండి')
k('commonRefresh', 'Refresh', 'रीफ़्रेश करें', 'రిఫ్రెష్ చేయండి')
k('commonSave', 'Save', 'सहेजें', 'సేవ్ చేయండి')
k('commonCancel', 'Cancel', 'रद्द करें', 'రద్దు చేయండి')
k('commonConfirm', 'Confirm', 'पुष्टि करें', 'నిర్ధారించండి')
k('commonContinue', 'Continue', 'जारी रखें', 'కొనసాగించండి')
k('commonDiscard', 'Discard', 'हटाएँ', 'విస్మరించండి')
k('commonAdd', 'Add', 'जोड़ें', 'జోడించండి')
k('commonRemove', 'Remove', 'हटाएँ', 'తొలగించండి')
k('commonOk', 'OK', 'ठीक है', 'సరే')
k('commonLogout', 'Log out', 'लॉग आउट', 'లాగ్ అవుట్')
k('copied', 'Copied', 'कॉपी हो गया', 'కాపీ అయింది')
k('send', 'Send', 'भेजें', 'పంపండి')
k('fieldRequired', 'Required', 'आवश्यक', 'అవసరం')
k('linkFailed', "Couldn't open the link", 'लिंक नहीं खुल सका', 'లింక్ తెరవలేకపోయాం')
k('offlineBanner', "You're offline. Showing the last loaded data.", 'आप ऑफ़लाइन हैं। पिछला लोड किया गया डेटा दिख रहा है।', 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు. చివరిగా లోడ్ చేసిన డేటా చూపిస్తున్నాం.')
k('statusLabel', 'Status', 'स्थिति', 'స్థితి')
k('priorityLabel', 'Priority', 'प्राथमिकता', 'ప్రాధాన్యత')
k('severityLabel', 'Severity', 'गंभीरता', 'తీవ్రత')
k('episodeLabel', 'Care episode', 'केयर एपिसोड', 'కేర్ ఎపిసోడ్')
k('reasonLabel', 'Reason', 'कारण', 'కారణం')
k('noneRecorded', 'None recorded', 'कुछ दर्ज नहीं', 'ఏదీ నమోదు కాలేదు')
k('noneAdded', 'Nothing added yet', 'अभी कुछ नहीं जोड़ा गया', 'ఇంకా ఏదీ జోడించలేదు')
k('onePerLine', 'One per line', 'हर पंक्ति में एक', 'ఒక్కో లైన్‌కు ఒకటి')
k('commaSeparated', 'Separate with commas', 'कॉमा से अलग करें', 'కామాలతో వేరు చేయండి')
k('ageYears', '{age} y', '{age} वर्ष', '{age} సం')
k('daysCount', '{count} days', '{count} दिन', '{count} రోజులు')
k('genderMale', 'Male', 'पुरुष', 'పురుషుడు')
k('genderFemale', 'Female', 'महिला', 'స్త్రీ')
k('genderOther', 'Other', 'अन्य', 'ఇతర')
k('errorNetwork', "Can't reach CareCompanion. Check your connection.", 'केयरकम्पैनियन से जुड़ नहीं पा रहे। कनेक्शन जाँचें।', 'కేర్‌కంపానియన్‌ను చేరలేకపోతున్నాం. కనెక్షన్ తనిఖీ చేయండి.')
k('errorGeneric', 'Something went wrong. Please try again.', 'कुछ गलत हो गया। फिर से कोशिश करें।', 'ఏదో తప్పు జరిగింది. మళ్లీ ప్రయత్నించండి.')
k('errorServer', 'The service is having trouble. Please try again shortly.', 'सेवा में समस्या है। थोड़ी देर बाद कोशिश करें।', 'సేవలో సమస్య ఉంది. కొద్దిసేపటి తర్వాత ప్రయత్నించండి.')
k('errorSessionExpired', 'Your session expired. Please log in again.', 'आपका सत्र समाप्त हो गया। फिर से लॉग इन करें।', 'మీ సెషన్ ముగిసింది. మళ్లీ లాగిన్ అవ్వండి.')
k('errorForbidden', "You don't have access to this.", 'आपको इसकी अनुमति नहीं है।', 'దీనికి మీకు అనుమతి లేదు.')
k('errorNotFound', 'This item is no longer available.', 'यह अब उपलब्ध नहीं है।', 'ఇది ఇక అందుబాటులో లేదు.')
k('errorRateLimited', 'Too many attempts. Please wait and try again.', 'बहुत सारे प्रयास। कुछ देर रुककर कोशिश करें।', 'చాలా ప్రయత్నాలు. కొంతసేపు ఆగి ప్రయత్నించండి.')
k('errorMfaRequired', 'Two-step verification is required to continue.', 'जारी रखने के लिए दो-चरणीय सत्यापन ज़रूरी है।', 'కొనసాగడానికి రెండు-దశల ధృవీకరణ అవసరం.')

# ------------------------------------------------------------------ Login
k('loginTitle', 'Doctor sign in', 'डॉक्टर साइन इन', 'డాక్టర్ సైన్ ఇన్')
k('loginSubtitle', 'Your queue, patients and care team in one place.', 'आपकी कतार, मरीज़ और केयर टीम एक जगह।', 'మీ క్యూ, రోగులు, కేర్ టీమ్ ఒకే చోట.')
k('loginPhoneLabel', 'Mobile number', 'मोबाइल नंबर', 'మొబైల్ నంబర్')
k('loginPhoneHint', '10-digit number', '10 अंकों का नंबर', '10 అంకెల నంబర్')
k('loginPhoneInvalid', 'Enter a valid 10-digit mobile number', 'सही 10 अंकों का मोबाइल नंबर डालें', 'సరైన 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి')
k('loginSendOtp', 'Send OTP', 'OTP भेजें', 'OTP పంపండి')
k('loginOtpSentTo', 'Enter the code sent to {phone}', '{phone} पर भेजा गया कोड डालें', '{phone}కి పంపిన కోడ్ నమోదు చేయండి')
k('loginOtpLabel', '6-digit OTP', '6 अंकों का OTP', '6 అంకెల OTP')
k('loginOtpInvalid', 'Enter the 6-digit code', '6 अंकों का कोड डालें', '6 అంకెల కోడ్ నమోదు చేయండి')
k('loginDevOtpHint', 'Development OTP: {code}', 'डेवलपमेंट OTP: {code}', 'డెవలప్‌మెంట్ OTP: {code}')
k('loginVerify', 'Verify', 'सत्यापित करें', 'ధృవీకరించండి')
k('loginChangeNumber', 'Change number', 'नंबर बदलें', 'నంబర్ మార్చండి')

# ------------------------------------------------------------------ MFA
k('mfaTitle', 'Two-step verification', 'दो-चरणीय सत्यापन', 'రెండు-దశల ధృవీకరణ')
k('mfaEnrolIntro', 'Doctor accounts are protected with an authenticator app code in addition to the SMS OTP.', 'डॉक्टर खाते SMS OTP के साथ ऑथेंटिकेटर ऐप कोड से सुरक्षित होते हैं।', 'డాక్టర్ ఖాతాలు SMS OTPతో పాటు ఆథెంటికేటర్ యాప్ కోడ్‌తో రక్షించబడతాయి.')
k('mfaStep1', '1. Add CareCompanion to your authenticator', '1. अपने ऑथेंटिकेटर में केयरकम्पैनियन जोड़ें', '1. మీ ఆథెంటికేటర్‌లో కేర్‌కంపానియన్ జోడించండి')
k('mfaStep2', '2. Enter the 6-digit code it shows', '2. वहाँ दिखा 6 अंकों का कोड डालें', '2. అక్కడ చూపిన 6 అంకెల కోడ్ నమోదు చేయండి')
k('mfaOpenAppHint', 'Tap the button to add the account automatically, or type the setup key into the app.', 'खाता अपने-आप जोड़ने के लिए बटन दबाएँ, या सेटअप कुंजी ऐप में टाइप करें।', 'ఖాతాను ఆటోమేటిక్‌గా జోడించడానికి బటన్ నొక్కండి, లేదా సెటప్ కీని యాప్‌లో టైప్ చేయండి.')
k('mfaOpenAuthenticator', 'Open authenticator app', 'ऑथेंटिकेटर ऐप खोलें', 'ఆథెంటికేటర్ యాప్ తెరవండి')
k('mfaSecretLabel', 'Setup key', 'सेटअप कुंजी', 'సెటప్ కీ')
k('mfaCopySecret', 'Copy setup key', 'सेटअप कुंजी कॉपी करें', 'సెటప్ కీ కాపీ చేయండి')
k('mfaCodeLabel', 'Authenticator code', 'ऑथेंटिकेटर कोड', 'ఆథెంటికేటర్ కోడ్')
k('mfaTurnOn', 'Verify and turn on', 'सत्यापित करें और चालू करें', 'ధృవీకరించి ఆన్ చేయండి')
k('mfaRecoveryIntro', 'Save these recovery codes somewhere safe. Each works once if you lose your phone. They will not be shown again.', 'ये रिकवरी कोड सुरक्षित रखें। फ़ोन खोने पर हर कोड एक बार काम करेगा। ये दोबारा नहीं दिखेंगे।', 'ఈ రికవరీ కోడ్‌లను సురక్షితంగా ఉంచండి. ఫోన్ పోతే ఒక్కో కోడ్ ఒకసారి పనిచేస్తుంది. ఇవి మళ్లీ చూపబడవు.')
k('mfaCopyCodes', 'Copy all codes', 'सभी कोड कॉपी करें', 'అన్ని కోడ్‌లు కాపీ చేయండి')
k('mfaSavedCodes', "I've saved my recovery codes", 'मैंने रिकवरी कोड सहेज लिए हैं', 'నేను రికవరీ కోడ్‌లను సేవ్ చేశాను')
k('mfaVerifyPrompt', 'Enter the 6-digit code from your authenticator app.', 'अपने ऑथेंटिकेटर ऐप से 6 अंकों का कोड डालें।', 'మీ ఆథెంటికేటర్ యాప్ నుండి 6 అంకెల కోడ్ నమోదు చేయండి.')
k('mfaRecoveryPrompt', 'Enter one of your recovery codes. Each code works only once.', 'अपना एक रिकवरी कोड डालें। हर कोड एक ही बार काम करता है।', 'మీ రికవరీ కోడ్‌లలో ఒకటి నమోదు చేయండి. ఒక్కో కోడ్ ఒకసారే పనిచేస్తుంది.')
k('mfaRecoveryLabel', 'Recovery code', 'रिकवरी कोड', 'రికవరీ కోడ్')
k('mfaVerify', 'Verify', 'सत्यापित करें', 'ధృవీకరించండి')
k('mfaUseRecovery', 'Use a recovery code instead', 'इसके बजाय रिकवरी कोड इस्तेमाल करें', 'బదులుగా రికవరీ కోడ్ ఉపయోగించండి')
k('mfaUseAuthenticator', 'Use the authenticator app', 'ऑथेंटिकेटर ऐप इस्तेमाल करें', 'ఆథెంటికేటర్ యాప్ ఉపయోగించండి')
k('mfaWrongCode', 'That code is incorrect.', 'यह कोड गलत है।', 'ఆ కోడ్ తప్పు.')
k('mfaWrongCodeAttempts', 'That code is incorrect. {count} attempts left.', 'यह कोड गलत है। {count} प्रयास बाकी।', 'ఆ కోడ్ తప్పు. ఇంకా {count} ప్రయత్నాలు.')
k('mfaCodeInvalid', 'Enter the 6-digit code', '6 अंकों का कोड डालें', '6 అంకెల కోడ్ నమోదు చేయండి')
k('mfaRecoveryInvalid', 'Enter a valid recovery code', 'सही रिकवरी कोड डालें', 'సరైన రికవరీ కోడ్ నమోదు చేయండి')
k('mfaLocked', 'Too many incorrect codes. Try again in 15 minutes.', 'बहुत सारे गलत कोड। 15 मिनट बाद कोशिश करें।', 'చాలా తప్పు కోడ్‌లు. 15 నిమిషాల తర్వాత ప్రయత్నించండి.')
k('mfaStatusOn', 'On (authenticator app)', 'चालू (ऑथेंटिकेटर ऐप)', 'ఆన్ (ఆథెంటికేటర్ యాప్)')
k('mfaStatusOff', 'Not set up yet. You will be asked when your organisation requires it.', 'अभी सेट नहीं है। संस्था के कहने पर पूछा जाएगा।', 'ఇంకా సెట్ చేయలేదు. మీ సంస్థ అడిగినప్పుడు అడుగుతాం.')

# ------------------------------------------------------------------ Gates
k('restrictedTitle', 'This app is for doctors', 'यह ऐप डॉक्टरों के लिए है', 'ఈ యాప్ డాక్టర్ల కోసం')
k('restrictedBody', 'Your account does not have a verified doctor profile.', 'आपके खाते में सत्यापित डॉक्टर प्रोफ़ाइल नहीं है।', 'మీ ఖాతాకు ధృవీకరించిన డాక్టర్ ప్రొఫైల్ లేదు.')
k('restrictedPatient', 'Please use the CareCompanion app for patients and families.', 'कृपया मरीज़ों और परिवारों के लिए केयरकम्पैनियन ऐप इस्तेमाल करें।', 'దయచేసి రోగులు, కుటుంబాల కోసం కేర్‌కంపానియన్ యాప్ ఉపయోగించండి.')
k('restrictedProvider', 'Please use the CareCompanion Pro app for home-care visits.', 'होम-केयर विज़िट के लिए कृपया केयरकम्पैनियन प्रो ऐप इस्तेमाल करें।', 'హోమ్-కేర్ విజిట్‌ల కోసం దయచేసి కేర్‌కంపానియన్ ప్రో యాప్ ఉపయోగించండి.')
k('restrictedStaff', 'Please use the CareCompanion web portal for your role.', 'अपनी भूमिका के लिए कृपया केयरकम्पैनियन वेब पोर्टल इस्तेमाल करें।', 'మీ పాత్ర కోసం దయచేసి కేర్‌కంపానియన్ వెబ్ పోర్టల్ ఉపయోగించండి.')
k('updateTitle', 'Please update the app', 'कृपया ऐप अपडेट करें', 'దయచేసి యాప్‌ను అప్‌డేట్ చేయండి')
k('updateBody', 'This version is no longer supported. Update to keep seeing patients safely.', 'यह संस्करण अब समर्थित नहीं है। सुरक्षित रूप से काम जारी रखने के लिए अपडेट करें।', 'ఈ వెర్షన్‌కు ఇక మద్దతు లేదు. సురక్షితంగా కొనసాగడానికి అప్‌డేట్ చేయండి.')
k('updateNow', 'Update now', 'अभी अपडेट करें', 'ఇప్పుడే అప్‌డేట్ చేయండి')
k('updateVersions', 'Installed {current} · required {minimum}', 'इंस्टॉल {current} · आवश्यक {minimum}', 'ఇన్‌స్టాల్ {current} · అవసరం {minimum}')
k('supportTitle', 'Support', 'सहायता', 'సహాయం')
k('supportCall', 'Call support', 'सहायता को कॉल करें', 'సహాయానికి కాల్ చేయండి')
k('supportEmail', 'Email support', 'सहायता को ईमेल करें', 'సహాయానికి ఈమెయిల్ చేయండి')
k('supportWhatsapp', 'WhatsApp support', 'व्हाट्सऐप सहायता', 'వాట్సాప్ సహాయం')

# ------------------------------------------------------------------ Nav / Today
k('navToday', 'Today', 'आज', 'ఈరోజు')
k('navPatients', 'Patients', 'मरीज़', 'రోగులు')
k('navMessages', 'Messages', 'संदेश', 'సందేశాలు')
k('navMore', 'More', 'और', 'మరిన్ని')
k('helloDoctor', 'Hello, {name}', 'नमस्ते, {name}', 'నమస్తే, {name}')
k('queueEmpty', 'No consultations on this day.', 'इस दिन कोई परामर्श नहीं।', 'ఈ రోజు సంప్రదింపులు లేవు.')
k('queueWaiting', 'Waiting', 'प्रतीक्षा में', 'వేచి ఉన్నవి')
k('queueInProgress', 'In progress', 'जारी', 'జరుగుతున్నవి')
k('queueDone', 'Done', 'पूरा', 'పూర్తయినవి')
k('apptPendingPayment', 'Payment pending', 'भुगतान बाकी', 'చెల్లింపు పెండింగ్')
k('apptConfirmed', 'Confirmed', 'पुष्ट', 'నిర్ధారించబడింది')
k('apptInProgress', 'In progress', 'जारी', 'జరుగుతోంది')
k('apptCompleted', 'Completed', 'पूरा', 'పూర్తయింది')
k('apptCancelled', 'Cancelled', 'रद्द', 'రద్దు')
k('apptNoShow', 'No-show', 'नहीं आए', 'హాజరు కాలేదు')
k('priorityRoutine', 'Routine', 'सामान्य', 'సాధారణం')
k('priorityUrgent', 'Urgent', 'तत्काल', 'అత్యవసరం')
k('priorityEmergency', 'Emergency', 'आपातकाल', 'అత్యవసర పరిస్థితి')
k('epNew', 'New', 'नया', 'కొత్తది')
k('epIntake', 'Intake', 'इनटेक', 'ఇన్‌టేక్')
k('epAwaitingCare', 'Awaiting care', 'देखभाल की प्रतीक्षा', 'సంరక్షణ కోసం వేచి')
k('epCareScheduled', 'Care scheduled', 'देखभाल तय', 'సంరక్షణ షెడ్యూల్')
k('epUnderCare', 'Under care', 'देखभाल में', 'సంరక్షణలో')
k('epFollowUp', 'Follow-up', 'फ़ॉलो-अप', 'ఫాలో-అప్')
k('epResolved', 'Resolved', 'हल', 'పరిష్కరించబడింది')
k('epEscalated', 'Escalated', 'एस्केलेट किया गया', 'ఎస్కలేట్ చేయబడింది')
k('epEmergency', 'Emergency', 'आपातकाल', 'అత్యవసర పరిస్థితి')
k('epTransferred', 'Transferred', 'स्थानांतरित', 'బదిలీ చేయబడింది')
k('epCancelled', 'Cancelled', 'रद्द', 'రద్దు')
k('modeVideo', 'Video', 'वीडियो', 'వీడియో')
k('modeAudio', 'Audio', 'ऑडियो', 'ఆడియో')
k('modeChat', 'Chat', 'चैट', 'చాట్')
k('modeInClinic', 'In clinic', 'क्लिनिक में', 'క్లినిక్‌లో')
k('modeHomeVisit', 'Home visit', 'होम विज़िट', 'హోమ్ విజిట్')

# ------------------------------------------------------------------ Consultation
k('consultTitle', 'Consultation', 'परामर्श', 'సంప్రదింపు')
k('openPatient', 'Open patient record', 'मरीज़ का रिकॉर्ड खोलें', 'రోగి రికార్డు తెరవండి')
k('startConsult', 'Start consultation', 'परामर्श शुरू करें', 'సంప్రదింపు ప్రారంభించండి')
k('completeConsult', 'Complete consultation', 'परामर्श पूरा करें', 'సంప్రదింపు పూర్తి చేయండి')
k('consultStarted', 'Consultation started', 'परामर्श शुरू हुआ', 'సంప్రదింపు ప్రారంభమైంది')
k('consultCompleted', 'Consultation completed', 'परामर्श पूरा हुआ', 'సంప్రదింపు పూర్తయింది')
k('savedNotes', 'Saved notes', 'सहेजे गए नोट्स', 'సేవ్ చేసిన నోట్స్')
k('outcomeLabel', 'Outcome', 'परिणाम', 'ఫలితం')
k('outcomeCarePlan', 'Care plan', 'केयर प्लान', 'కేర్ ప్లాన్')
k('outcomeResolved', 'Resolved', 'हल', 'పరిష్కరించబడింది')
k('outcomeRefer', 'Refer', 'रेफ़र', 'రిఫర్')
k('outcomeHomeVisit', 'Home visit', 'होम विज़िट', 'హోమ్ విజిట్')
k('notesTitle', 'Clinical notes', 'क्लिनिकल नोट्स', 'క్లినికల్ నోట్స్')
k('notesHint', 'Type your notes, or use the AI scribe', 'नोट्स लिखें या AI स्क्राइब इस्तेमाल करें', 'నోట్స్ టైప్ చేయండి లేదా AI స్క్రైబ్ ఉపయోగించండి')
k('notesSaveHint', 'Notes are saved when you complete the consultation.', 'परामर्श पूरा करने पर नोट्स सहेजे जाते हैं।', 'సంప్రదింపు పూర్తి చేసినప్పుడు నోట్స్ సేవ్ అవుతాయి.')
k('saveEpisodeNote', 'Add to care episode now', 'अभी केयर एपिसोड में जोड़ें', 'ఇప్పుడే కేర్ ఎపిసోడ్‌కు జోడించండి')
k('noteSaved', 'Note added to the care episode', 'नोट केयर एपिसोड में जुड़ गया', 'నోట్ కేర్ ఎపిసోడ్‌కు జోడించబడింది')
k('toolsTitle', 'Actions', 'कार्य', 'చర్యలు')
k('careTeamThread', 'Care-team messages', 'केयर टीम संदेश', 'కేర్ టీమ్ సందేశాలు')
k('joinVideo', 'Join video', 'वीडियो से जुड़ें', 'వీడియోలో చేరండి')
k('videoTitle', 'Video consultation', 'वीडियो परामर्श', 'వీడియో సంప్రదింపు')
k('videoWindow', 'Room open', 'रूम खुला', 'రూమ్ తెరిచి ఉంటుంది')
k('videoAudioHint', 'Audio consultation: keep your camera off.', 'ऑडियो परामर्श: कैमरा बंद रखें।', 'ఆడియో సంప్రదింపు: కెమెరా ఆఫ్‌లో ఉంచండి.')
k('videoOpensAt', 'The room opens at {time} (10 minutes before the start).', 'रूम {time} पर खुलेगा (शुरू होने से 10 मिनट पहले)।', 'రూమ్ {time}కి తెరుచుకుంటుంది (ప్రారంభానికి 10 నిమిషాల ముందు).')
k('intakeTitle', 'Presenting complaint (AI intake)', 'मुख्य शिकायत (AI इनटेक)', 'ప్రధాన ఫిర్యాదు (AI ఇన్‌టేక్)')
k('intakeComplaint', 'Chief complaint', 'मुख्य शिकायत', 'ప్రధాన ఫిర్యాదు')
k('intakeDuration', 'Duration', 'अवधि', 'వ్యవధి')
k('intakeSeverity', 'Severity', 'गंभीरता', 'తీవ్రత')
k('intakeSymptoms', 'Associated symptoms', 'संबंधित लक्षण', 'సంబంధిత లక్షణాలు')
k('allergiesTitle', 'Allergies', 'एलर्जी', 'అలెర్జీలు')
k('allergiesNone', 'No known allergies recorded', 'कोई ज्ञात एलर्जी दर्ज नहीं', 'తెలిసిన అలెర్జీలు నమోదు కాలేదు')
k('conditionsTitle', 'Conditions', 'स्थितियाँ', 'పరిస్థితులు')
k('activeMedsTitle', 'Active medications', 'चालू दवाइयाँ', 'ప్రస్తుత మందులు')
k('recentVitalsTitle', 'Recent vitals', 'हाल के वाइटल्स', 'ఇటీవలి వైటల్స్')
k('homeVisitFindingsTitle', 'Home-visit findings', 'होम विज़िट निष्कर्ष', 'హోమ్ విజిట్ ఫలితాలు')
k('escalatedLabel', 'Escalated', 'एस्केलेट किया गया', 'ఎస్కలేట్ చేయబడింది')
k('aiSummaryTitle', 'AI summary', 'AI सारांश', 'AI సారాంశం')
k('aiAdvisoryLabel', 'AI-generated · advisory, not a diagnosis', 'AI द्वारा बनाया गया · केवल सलाह, निदान नहीं', 'AI రూపొందించినది · సలహా మాత్రమే, నిర్ధారణ కాదు')
k('aiSource', 'Source', 'स्रोत', 'మూలం')
k('aiFeedbackPrompt', 'Was this summary accurate?', 'क्या यह सारांश सही था?', 'ఈ సారాంశం ఖచ్చితంగా ఉందా?')
k('aiAccept', 'Accurate', 'सही', 'ఖచ్చితం')
k('aiReject', 'Not accurate', 'सही नहीं', 'ఖచ్చితం కాదు')
k('aiFeedbackThanks', 'Thanks, your feedback was recorded.', 'धन्यवाद, आपकी प्रतिक्रिया दर्ज हुई।', 'ధన్యవాదాలు, మీ అభిప్రాయం నమోదైంది.')
k('aiRecordSummary', 'AI record summary', 'AI रिकॉर्ड सारांश', 'AI రికార్డు సారాంశం')
k('srcRecord', 'Record', 'रिकॉर्ड', 'రికార్డు')
k('srcVital', 'Vital', 'वाइटल', 'వైటల్')
k('srcIntake', 'Intake', 'इनटेक', 'ఇన్‌టేక్')
k('srcHomeVisit', 'Home visit', 'होम विज़िट', 'హోమ్ విజిట్')
k('srcPatientEntered', 'Patient entered', 'मरीज़ द्वारा दर्ज', 'రోగి నమోదు చేసినది')

# ------------------------------------------------------------------ Scribe
k('scribeTitle', 'AI scribe', 'AI स्क्राइब', 'AI స్క్రైబ్')
k('scribeConsent', 'The patient agreed to this consultation being recorded and transcribed', 'मरीज़ ने इस परामर्श की रिकॉर्डिंग और लिप्यंतरण के लिए सहमति दी है', 'ఈ సంప్రదింపును రికార్డ్ చేసి లిప్యంతరీకరించడానికి రోగి అంగీకరించారు')
k('scribeConsentHint', 'Required before recording or sending a transcript. This is audited.', 'रिकॉर्डिंग या ट्रांसक्रिप्ट भेजने से पहले ज़रूरी। इसका ऑडिट होता है।', 'రికార్డింగ్ లేదా ట్రాన్స్‌క్రిప్ట్ పంపే ముందు అవసరం. ఇది ఆడిట్ అవుతుంది.')
k('scribeConsentRequired', "Confirm the patient's consent first.", 'पहले मरीज़ की सहमति की पुष्टि करें।', 'ముందుగా రోగి అంగీకారాన్ని నిర్ధారించండి.')
k('scribeRecordTitle', 'Record the consultation', 'परामर्श रिकॉर्ड करें', 'సంప్రదింపును రికార్డ్ చేయండి')
k('scribeRecord', 'Record', 'रिकॉर्ड करें', 'రికార్డ్ చేయండి')
k('scribeRecording', 'Recording…', 'रिकॉर्डिंग…', 'రికార్డ్ అవుతోంది…')
k('scribeStopUpload', 'Stop and create draft', 'रोकें और ड्राफ़्ट बनाएँ', 'ఆపి డ్రాఫ్ట్ సృష్టించండి')
k('scribeAudioNote', 'Audio is uploaded once, transcribed and then discarded by the server.', 'ऑडियो एक बार अपलोड होता है, लिप्यंतरण के बाद सर्वर उसे हटा देता है।', 'ఆడియో ఒకసారి అప్‌లోడ్ అవుతుంది, లిప్యంతరీకరణ తర్వాత సర్వర్ తొలగిస్తుంది.')
k('scribeTranscriptTitle', 'Or type / paste a transcript', 'या ट्रांसक्रिप्ट लिखें / चिपकाएँ', 'లేదా ట్రాన్స్‌క్రిప్ట్ టైప్ / పేస్ట్ చేయండి')
k('scribeTranscriptHint', 'Doctor: … Patient: …', 'डॉक्टर: … मरीज़: …', 'డాక్టర్: … రోగి: …')
k('scribeGenerate', 'Create SOAP draft', 'SOAP ड्राफ़्ट बनाएँ', 'SOAP డ్రాఫ్ట్ సృష్టించండి')
k('scribeDraftTitle', 'SOAP draft', 'SOAP ड्राफ़्ट', 'SOAP డ్రాఫ్ట్')
k('scribeInsert', 'Insert into notes', 'नोट्स में जोड़ें', 'నోట్స్‌లో చేర్చండి')
k('scribeInserted', 'Draft inserted. Review and edit before completing.', 'ड्राफ़्ट जोड़ा गया। पूरा करने से पहले जाँचें और बदलें।', 'డ్రాఫ్ట్ చేర్చబడింది. పూర్తి చేసే ముందు సమీక్షించి సవరించండి.')
k('scribeMicDenied', 'Microphone permission is needed to record.', 'रिकॉर्ड करने के लिए माइक्रोफ़ोन अनुमति चाहिए।', 'రికార్డ్ చేయడానికి మైక్రోఫోన్ అనుమతి అవసరం.')
k('scribeTranscriptShort', 'The transcript is too short.', 'ट्रांसक्रिप्ट बहुत छोटा है।', 'ట్రాన్స్‌క్రిప్ట్ చాలా చిన్నది.')
k('scribeTooLarge', 'The recording is larger than 25 MB. Record a shorter segment.', 'रिकॉर्डिंग 25 MB से बड़ी है। छोटा हिस्सा रिकॉर्ड करें।', 'రికార్డింగ్ 25 MB కంటే పెద్దది. చిన్న భాగాన్ని రికార్డ్ చేయండి.')
k('soapS', 'Subjective', 'सब्जेक्टिव', 'సబ్జెక్టివ్')
k('soapO', 'Objective', 'ऑब्जेक्टिव', 'ఆబ్జెక్టివ్')
k('soapA', 'Assessment', 'आकलन', 'అంచనా')
k('soapP', 'Plan', 'योजना', 'ప్రణాళిక')

# ------------------------------------------------------------------ Prescription
k('rxTitle', 'Prescription', 'प्रिस्क्रिप्शन', 'ప్రిస్క్రిప్షన్')
k('rxFor', 'For {name}', '{name} के लिए', '{name} కోసం')
k('rxItems', 'Medicines', 'दवाइयाँ', 'మందులు')
k('rxNoItems', 'Add at least one medicine.', 'कम से कम एक दवा जोड़ें।', 'కనీసం ఒక మందు జోడించండి.')
k('rxNeedsStart', 'Start the consultation first', 'पहले परामर्श शुरू करें', 'ముందుగా సంప్రదింపు ప్రారంభించండి')
k('rxItemTitle', 'Medicine', 'दवा', 'మందు')
k('rxDrugName', 'Medicine name', 'दवा का नाम', 'మందు పేరు')
k('rxStrength', 'Strength', 'शक्ति', 'బలం')
k('rxForm', 'Form', 'रूप', 'రూపం')
k('rxDose', 'Dose', 'खुराक', 'మోతాదు')
k('rxFrequency', 'Frequency', 'आवृत्ति', 'ఫ్రీక్వెన్సీ')
k('rxTiming', 'Timing', 'समय', 'సమయం')
k('rxTimingHint', 'After food', 'खाने के बाद', 'భోజనం తర్వాత')
k('rxDuration', 'Days', 'दिन', 'రోజులు')
k('rxDurationInvalid', '1–365 days', '1–365 दिन', '1–365 రోజులు')
k('rxTimes', 'Reminder times (HH:MM)', 'रिमाइंडर समय (HH:MM)', 'రిమైండర్ సమయాలు (HH:MM)')
k('rxTimesInvalid', 'Use 24-hour times like 08:00, 20:00', '08:00, 20:00 जैसे 24-घंटे का समय लिखें', '08:00, 20:00 వంటి 24 గంటల సమయాలు వాడండి')
k('rxInstructions', 'Instructions', 'निर्देश', 'సూచనలు')
k('rxChecksTitle', 'Interaction & allergy check', 'इंटरैक्शन और एलर्जी जाँच', 'ఇంటరాక్షన్ & అలెర్జీ తనిఖీ')
k('rxCheckIdle', 'Checks run automatically as you add medicines.', 'दवाएँ जोड़ते ही जाँच अपने-आप होती है।', 'మందులు జోడించగానే తనిఖీలు ఆటోమేటిక్‌గా జరుగుతాయి.')
k('rxChecking', 'Checking…', 'जाँच हो रही है…', 'తనిఖీ చేస్తోంది…')
k('rxNoWarnings', 'No interactions or allergy conflicts found.', 'कोई इंटरैक्शन या एलर्जी टकराव नहीं मिला।', 'ఇంటరాక్షన్‌లు లేదా అలెర్జీ విభేదాలు కనబడలేదు.')
k('rxPack', 'Knowledge pack {pack}', 'नॉलेज पैक {pack}', 'నాలెడ్జ్ ప్యాక్ {pack}')
k('sevMajor', 'Major', 'गंभीर', 'తీవ్రమైనది')
k('sevModerate', 'Moderate', 'मध्यम', 'మధ్యస్థం')
k('sevInfo', 'Info', 'जानकारी', 'సమాచారం')
k('warnAllergy', 'Allergy', 'एलर्जी', 'అలెర్జీ')
k('warnDuplicate', 'Duplicate therapy', 'दोहरा उपचार', 'నకిలీ చికిత్స')
k('warnInteraction', 'Interaction', 'इंटरैक्शन', 'ఇంటరాక్షన్')
k('warnDoseForm', 'Dose / form', 'खुराक / रूप', 'మోతాదు / రూపం')
k('rxAcknowledge', 'I have reviewed the major warnings and still want to prescribe', 'मैंने गंभीर चेतावनियाँ देख ली हैं और फिर भी लिखना चाहता/चाहती हूँ', 'నేను తీవ్ర హెచ్చరికలను సమీక్షించాను, అయినా రాయాలనుకుంటున్నాను')
k('rxOverrideReason', 'Clinical reason for overriding', 'ओवरराइड का क्लिनिकल कारण', 'ఓవర్‌రైడ్ చేయడానికి క్లినికల్ కారణం')
k('rxOverrideReasonHint', 'At least {min} characters. Audited.', 'कम से कम {min} अक्षर। ऑडिट होता है।', 'కనీసం {min} అక్షరాలు. ఆడిట్ అవుతుంది.')
k('rxMajorBlocked', 'Major warnings need your acknowledgement and a reason.', 'गंभीर चेतावनियों के लिए स्वीकृति और कारण ज़रूरी है।', 'తీవ్ర హెచ్చరికలకు మీ అంగీకారం, కారణం అవసరం.')
k('rxClinicalNote', 'Clinical note (on the prescription)', 'क्लिनिकल नोट (प्रिस्क्रिप्शन पर)', 'క్లినికల్ నోట్ (ప్రిస్క్రిప్షన్‌పై)')
k('rxAdvice', 'Advice', 'सलाह', 'సలహా')
k('rxFollowUpDays', 'Follow up in (days)', 'फ़ॉलो-अप (दिन में)', 'ఫాలో-అప్ (రోజుల్లో)')
k('rxSign', 'Create prescription', 'प्रिस्क्रिप्शन बनाएँ', 'ప్రిస్క్రిప్షన్ సృష్టించండి')
k('rxCreated', 'Prescription created and shared with the patient', 'प्रिस्क्रिप्शन बना और मरीज़ से साझा हुआ', 'ప్రిస్క్రిప్షన్ సృష్టించి రోగితో పంచుకున్నాం')
k('rxPdfTitle', 'Prescription · {name}', 'प्रिस्क्रिप्शन · {name}', 'ప్రిస్క్రిప్షన్ · {name}')
k('formTablet', 'Tablet', 'टैबलेट', 'టాబ్లెట్')
k('formCapsule', 'Capsule', 'कैप्सूल', 'క్యాప్సూల్')
k('formSyrup', 'Syrup', 'सिरप', 'సిరప్')
k('formInjection', 'Injection', 'इंजेक्शन', 'ఇంజెక్షన్')
k('formOintment', 'Ointment', 'मरहम', 'లేపనం')
k('formDrops', 'Drops', 'ड्रॉप्स', 'డ్రాప్స్')
k('formInhaler', 'Inhaler', 'इनहेलर', 'ఇన్‌హేలర్')
k('formOther', 'Other', 'अन्य', 'ఇతర')
k('pdfDocument', 'PDF document: {title}', 'PDF दस्तावेज़: {title}', 'PDF పత్రం: {title}')
k('pageOf', 'Page {page} of {total}', 'पेज {page} / {total}', 'పేజీ {page} / {total}')
k('fileReady', 'The file is ready. Open it in your browser to view it.', 'फ़ाइल तैयार है। देखने के लिए ब्राउज़र में खोलें।', 'ఫైల్ సిద్ధంగా ఉంది. చూడటానికి బ్రౌజర్‌లో తెరవండి.')
k('openInBrowser', 'Open in browser', 'ब्राउज़र में खोलें', 'బ్రౌజర్‌లో తెరవండి')

# ------------------------------------------------------------------ Care plan & forms
k('carePlanTitle', 'Care plan', 'केयर प्लान', 'కేర్ ప్లాన్')
k('carePlanSummary', 'Summary', 'सारांश', 'సారాంశం')
k('carePlanInstructions', 'Instructions for the patient', 'मरीज़ के लिए निर्देश', 'రోగికి సూచనలు')
k('carePlanTasks', 'Tasks', 'कार्य', 'పనులు')
k('carePlanMeds', 'Medications', 'दवाइयाँ', 'మందులు')
k('carePlanSaved', 'Care plan saved', 'केयर प्लान सहेजा गया', 'కేర్ ప్లాన్ సేవ్ అయింది')
k('taskTitle', 'Task', 'कार्य', 'పని')
k('taskType', 'Type', 'प्रकार', 'రకం')
k('taskOwner', 'Who', 'कौन', 'ఎవరు')
k('taskDueInDays', 'Due in (days, optional)', 'कितने दिन में (वैकल्पिक)', 'ఎన్ని రోజుల్లో (ఐచ్ఛికం)')
k('taskMedication', 'Medication', 'दवा', 'మందు')
k('taskTest', 'Test', 'जाँच', 'పరీక్ష')
k('taskFollowUp', 'Follow-up', 'फ़ॉलो-अप', 'ఫాలో-అప్')
k('taskLifestyle', 'Lifestyle', 'जीवनशैली', 'జీవనశైలి')
k('taskMonitoring', 'Monitoring', 'निगरानी', 'పర్యవేక్షణ')
k('taskGeneral', 'General', 'सामान्य', 'సాధారణం')
k('ownerPatient', 'Patient', 'मरीज़', 'రోగి')
k('ownerCaregiver', 'Caregiver', 'देखभालकर्ता', 'సంరక్షకులు')
k('ownerProvider', 'Care provider', 'केयर प्रोवाइडर', 'కేర్ ప్రొవైడర్')
k('followUpTitle', 'Follow-up', 'फ़ॉलो-अप', 'ఫాలో-అప్')
k('followUpAfterDays', 'After (days)', 'कितने दिन बाद', 'ఎన్ని రోజుల తర్వాత')
k('followUpMode', 'Mode', 'तरीका', 'విధానం')
k('followUpNone', 'No follow-up', 'कोई फ़ॉलो-अप नहीं', 'ఫాలో-అప్ లేదు')
k('referTitle', 'Refer to hospital', 'अस्पताल रेफ़र करें', 'ఆసుపత్రికి రిఫర్ చేయండి')
k('referSearchHospital', 'Search hospitals', 'अस्पताल खोजें', 'ఆసుపత్రులను వెతకండి')
k('referNoHospitals', 'No hospitals found.', 'कोई अस्पताल नहीं मिला।', 'ఆసుపత్రులు కనబడలేదు.')
k('referSpecialty', 'Specialty (optional)', 'विशेषज्ञता (वैकल्पिक)', 'స్పెషాలిటీ (ఐచ్ఛికం)')
k('referReason', 'Reason for referral', 'रेफ़रल का कारण', 'రిఫరల్ కారణం')
k('referSummary', 'Clinical summary (optional)', 'क्लिनिकल सारांश (वैकल्पिक)', 'క్లినికల్ సారాంశం (ఐచ్ఛికం)')
k('referSend', 'Create referral letter', 'रेफ़रल पत्र बनाएँ', 'రిఫరల్ లేఖ సృష్టించండి')
k('referSaved', 'Referral created. The patient has been notified.', 'रेफ़रल बना। मरीज़ को सूचित किया गया।', 'రిఫరల్ సృష్టించబడింది. రోగికి తెలియజేశాం.')
k('emergency24x7', '24×7 emergency', '24×7 आपातकालीन', '24×7 అత్యవసర')
k('enrolTitle', 'Enrol in care program', 'केयर प्रोग्राम में नामांकन', 'కేర్ ప్రోగ్రామ్‌లో నమోదు')
k('enrolThresholds', 'Alert thresholds', 'अलर्ट सीमाएँ', 'అలర్ట్ పరిమితులు')
k('enrolSave', 'Enrol patient', 'मरीज़ का नामांकन करें', 'రోగిని నమోదు చేయండి')
k('enrolSaved', 'Patient enrolled', 'मरीज़ का नामांकन हुआ', 'రోగి నమోదయ్యారు')
k('fixtureWarning', 'Template not yet clinically approved (fixture).', 'टेम्पलेट अभी क्लिनिकल रूप से स्वीकृत नहीं (फ़िक्स्चर)।', 'టెంప్లేట్ ఇంకా క్లినికల్‌గా ఆమోదించబడలేదు (ఫిక్స్చర్).')
k('exerciseTitle', 'Exercise plan', 'व्यायाम योजना', 'వ్యాయామ ప్రణాళిక')
k('exerciseWeeks', 'Weeks', 'सप्ताह', 'వారాలు')
k('exerciseSets', 'Sets', 'सेट', 'సెట్లు')
k('exerciseReps', 'Reps', 'रेप्स', 'రెప్స్')
k('exercisePerDay', 'Per day', 'प्रतिदिन', 'రోజుకు')
k('planSaved', 'Plan shared with the patient', 'योजना मरीज़ से साझा की गई', 'ప్రణాళిక రోగితో పంచుకున్నాం')
k('dietTitle', 'Diet plan', 'आहार योजना', 'ఆహార ప్రణాళిక')
k('dietTemplate', 'Template', 'टेम्पलेट', 'టెంప్లేట్')
k('dietNoTemplate', 'No template', 'कोई टेम्पलेट नहीं', 'టెంప్లేట్ లేదు')
k('dietConditions', 'Conditions (comma separated)', 'स्थितियाँ (कॉमा से अलग)', 'పరిస్థితులు (కామాలతో)')
k('dietCalories', 'Calorie target (optional)', 'कैलोरी लक्ष्य (वैकल्पिक)', 'కేలరీ లక్ష్యం (ఐచ్ఛికం)')
k('dietMeals', 'Meals', 'भोजन', 'భోజనాలు')
k('dietMealsHint', 'Separate items with commas.', 'आइटम कॉमा से अलग करें।', 'అంశాలను కామాలతో వేరు చేయండి.')
k('dietMealsCount', '{count} meals filled', '{count} भोजन भरे गए', '{count} భోజనాలు నింపారు')
k('dietNeedMeals', 'Choose a template or fill at least one meal.', 'टेम्पलेट चुनें या कम से कम एक भोजन भरें।', 'టెంప్లేట్ ఎంచుకోండి లేదా కనీసం ఒక భోజనం నింపండి.')
k('dietAvoid', 'Avoid (comma separated)', 'परहेज़ (कॉमा से अलग)', 'నివారించాల్సినవి (కామాలతో)')
k('dietNotes', 'Notes', 'नोट्स', 'నోట్స్')
k('dietValidWeeks', 'Valid for {weeks} weeks', '{weeks} सप्ताह तक मान्य', '{weeks} వారాలు చెల్లుబాటు')
k('slotEarlyMorning', 'Early morning', 'सुबह जल्दी', 'తెల్లవారుజామున')
k('slotBreakfast', 'Breakfast', 'नाश्ता', 'అల్పాహారం')
k('slotMidMorning', 'Mid-morning', 'दोपहर से पहले', 'మధ్యాహ్నం ముందు')
k('slotLunch', 'Lunch', 'दोपहर का भोजन', 'మధ్యాహ్న భోజనం')
k('slotEvening', 'Evening', 'शाम', 'సాయంత్రం')
k('slotDinner', 'Dinner', 'रात का भोजन', 'రాత్రి భోజనం')
k('slotBedtime', 'Bedtime', 'सोने से पहले', 'నిద్రకు ముందు')

# ------------------------------------------------------------------ Patients
k('patientTitle', 'Patient', 'मरीज़', 'రోగి')
k('patientSearchHint', 'Search your patients by name', 'नाम से अपने मरीज़ खोजें', 'పేరుతో మీ రోగులను వెతకండి')
k('patientsEmpty', 'Patients you consult or who share records with you appear here.', 'जिन मरीज़ों से आप परामर्श करते हैं या जो रिकॉर्ड साझा करते हैं, वे यहाँ दिखेंगे।', 'మీరు సంప్రదించిన లేదా రికార్డులు పంచుకున్న రోగులు ఇక్కడ కనిపిస్తారు.')
k('patientsNoMatch', 'No patients match your search.', 'खोज से कोई मरीज़ नहीं मिला।', 'మీ శోధనకు రోగులు సరిపోలలేదు.')
k('bloodGroup', 'Blood group', 'रक्त समूह', 'రక్త గ్రూప్')
k('tabOverview', 'Overview', 'सारांश', 'అవలోకనం')
k('tabRecords', 'Records', 'रिकॉर्ड', 'రికార్డులు')
k('tabVitals', 'Vitals', 'वाइटल्स', 'వైటల్స్')
k('tabPrograms', 'Programs', 'प्रोग्राम', 'ప్రోగ్రామ్‌లు')
k('tabPrescriptions', 'Prescriptions', 'प्रिस्क्रिप्शन', 'ప్రిస్క్రిప్షన్లు')
k('tabEpisodes', 'Episodes', 'एपिसोड', 'ఎపిసోడ్‌లు')
k('recordsEmpty', 'No records shared.', 'कोई रिकॉर्ड साझा नहीं।', 'రికార్డులు పంచుకోలేదు.')
k('openOriginal', 'Open original file', 'मूल फ़ाइल खोलें', 'అసలు ఫైల్ తెరవండి')
k('recLab', 'Lab report', 'लैब रिपोर्ट', 'ల్యాబ్ రిపోర్ట్')
k('recPrescription', 'Prescription', 'प्रिस्क्रिप्शन', 'ప్రిస్క్రిప్షన్')
k('recImaging', 'Imaging', 'इमेजिंग', 'ఇమేజింగ్')
k('recDischarge', 'Discharge summary', 'डिस्चार्ज सारांश', 'డిశ్చార్జ్ సారాంశం')
k('recVisitSummary', 'Visit summary', 'विज़िट सारांश', 'విజిట్ సారాంశం')
k('recOther', 'Other', 'अन्य', 'ఇతర')
k('vitalsEmpty', 'No vitals recorded.', 'कोई वाइटल्स दर्ज नहीं।', 'వైటల్స్ నమోదు కాలేదు.')
k('vitalRange', 'Range {min}–{max}', 'सीमा {min}–{max}', 'పరిధి {min}–{max}')
k('readingsCount', '{count} readings', '{count} रीडिंग', '{count} రీడింగ్‌లు')
k('vitalTrendSemantics', '{vital} trend: {count} readings between {min} and {max}', '{vital} रुझान: {min} से {max} के बीच {count} रीडिंग', '{vital} ధోరణి: {min} నుండి {max} మధ్య {count} రీడింగ్‌లు')
k('vitalBpSystolic', 'BP systolic', 'BP सिस्टोलिक', 'BP సిస్టోలిక్')
k('vitalBpDiastolic', 'BP diastolic', 'BP डायस्टोलिक', 'BP డయాస్టోలిక్')
k('vitalPulse', 'Pulse', 'नाड़ी', 'నాడి')
k('vitalSpo2', 'SpO2', 'SpO2', 'SpO2')
k('vitalTemperature', 'Temperature', 'तापमान', 'ఉష్ణోగ్రత')
k('vitalGlucose', 'Blood glucose', 'ब्लड ग्लूकोज़', 'రక్తంలో గ్లూకోజ్')
k('vitalWeight', 'Weight', 'वज़न', 'బరువు')
k('vitalRespiratoryRate', 'Respiratory rate', 'श्वसन दर', 'శ్వాస రేటు')
k('programsEmpty', 'Not enrolled in any care program.', 'किसी केयर प्रोग्राम में नामांकन नहीं।', 'ఏ కేర్ ప్రోగ్రామ్‌లోనూ నమోదు కాలేదు.')
k('programAdherence', 'Adherence (7 days)', 'पालन (7 दिन)', 'పాటించడం (7 రోజులు)')
k('programLastReading', 'Last reading', 'अंतिम रीडिंग', 'చివరి రీడింగ్')
k('programOpenBreaches', 'Open alerts', 'खुले अलर्ट', 'తెరిచిన అలర్ట్‌లు')
k('progActive', 'Active', 'सक्रिय', 'సక్రియం')
k('progPaused', 'Paused', 'रुका हुआ', 'నిలిపివేయబడింది')
k('progCompleted', 'Completed', 'पूरा', 'పూర్తయింది')
k('prescriptionsEmpty', 'No prescriptions yet.', 'अभी कोई प्रिस्क्रिप्शन नहीं।', 'ఇంకా ప్రిస్క్రిప్షన్లు లేవు.')
k('episodesEmpty', 'No care episodes.', 'कोई केयर एपिसोड नहीं।', 'కేర్ ఎపిసోడ్‌లు లేవు.')

# ------------------------------------------------------------------ Messages
k('inboxEmpty', 'No care-team conversations yet.', 'अभी कोई केयर टीम बातचीत नहीं।', 'ఇంకా కేర్ టీమ్ సంభాషణలు లేవు.')
k('noMessagesYet', 'No messages yet', 'अभी कोई संदेश नहीं', 'ఇంకా సందేశాలు లేవు')
k('unreadCount', '{count} unread', '{count} अपठित', '{count} చదవనివి')
k('messageHint', 'Message the care team', 'केयर टीम को संदेश भेजें', 'కేర్ టీమ్‌కు సందేశం పంపండి')
k('emergencyNotice', 'Emergency safety notice', 'आपातकालीन सुरक्षा सूचना', 'అత్యవసర భద్రతా సూచన')

# ------------------------------------------------------------------ More
k('secondOpinionsTitle', 'Second opinions', 'सेकंड ओपिनियन', 'సెకండ్ ఒపీనియన్')
k('soTabOpen', 'Open', 'खुले', 'తెరిచినవి')
k('soTabMine', 'Mine', 'मेरे', 'నావి')
k('soEmpty', 'No requests here.', 'यहाँ कोई अनुरोध नहीं।', 'ఇక్కడ అభ్యర్థనలు లేవు.')
k('soOpen', 'Open', 'खुला', 'తెరిచి ఉంది')
k('soClaimed', 'Claimed', 'लिया गया', 'తీసుకోబడింది')
k('soAnswered', 'Answered', 'उत्तर दिया', 'సమాధానం ఇచ్చారు')
k('soClaim', 'Claim', 'लें', 'తీసుకోండి')
k('soClaimedMsg', 'Request claimed. Records are now shared with you.', 'अनुरोध लिया गया। रिकॉर्ड अब आपसे साझा हैं।', 'అభ్యర్థన తీసుకున్నారు. రికార్డులు ఇప్పుడు మీతో పంచుకోబడ్డాయి.')
k('soRespond', 'Write opinion', 'राय लिखें', 'అభిప్రాయం రాయండి')
k('soOpinion', 'Opinion', 'राय', 'అభిప్రాయం')
k('soRecommendations', 'Recommendations', 'सिफ़ारिशें', 'సిఫార్సులు')
k('soSuggestTele', 'Suggest a teleconsultation', 'टेलीकंसल्टेशन सुझाएँ', 'టెలికన్సల్టేషన్ సూచించండి')
k('soSent', 'Opinion sent to the patient', 'राय मरीज़ को भेजी गई', 'అభిప్రాయం రోగికి పంపబడింది')
k('soDue', 'Due {date}', 'नियत {date}', 'గడువు {date}')
k('escalationsTitle', 'Escalations', 'एस्केलेशन', 'ఎస్కలేషన్‌లు')
k('escalationsEmpty', 'No escalations for your patients.', 'आपके मरीज़ों के लिए कोई एस्केलेशन नहीं।', 'మీ రోగులకు ఎస్కలేషన్‌లు లేవు.')
k('scheduleTitle', 'Schedule & leaves', 'शेड्यूल और छुट्टियाँ', 'షెడ్యూల్ & సెలవులు')
k('weeklyTab', 'Weekly hours', 'साप्ताहिक समय', 'వారపు గంటలు')
k('leavesTab', 'Leaves', 'छुट्टियाँ', 'సెలవులు')
k('scheduleHint', 'Saving regenerates unbooked slots for the next {days} days. Booked slots are never changed.', 'सहेजने पर अगले {days} दिनों के खाली स्लॉट फिर से बनते हैं। बुक स्लॉट नहीं बदलते।', 'సేవ్ చేస్తే తదుపరి {days} రోజుల ఖాళీ స్లాట్‌లు మళ్లీ సృష్టించబడతాయి. బుక్ అయిన స్లాట్‌లు మారవు.')
k('scheduleEmpty', 'No weekly hours yet.', 'अभी कोई साप्ताहिक समय नहीं।', 'ఇంకా వారపు గంటలు లేవు.')
k('addBlock', 'Add hours', 'समय जोड़ें', 'గంటలు జోడించండి')
k('blockTitle', 'Consultation hours', 'परामर्श का समय', 'సంప్రదింపు గంటలు')
k('weekday', 'Day', 'दिन', 'రోజు')
k('startTime', 'Start', 'शुरू', 'ప్రారంభం')
k('endTime', 'End', 'समाप्त', 'ముగింపు')
k('slotLength', 'Slot length', 'स्लॉट अवधि', 'స్లాట్ వ్యవధి')
k('slotMinutes', '{minutes} min', '{minutes} मिनट', '{minutes} నిమి')
k('blockInvalidTime', 'Invalid time', 'अमान्य समय', 'చెల్లని సమయం')
k('blockEndBeforeStart', 'End must be after start', 'समाप्ति शुरुआत के बाद होनी चाहिए', 'ముగింపు ప్రారంభం తర్వాత ఉండాలి')
k('blockTooShort', 'Shorter than one slot', 'एक स्लॉट से छोटा', 'ఒక స్లాట్ కంటే చిన్నది')
k('blockNoModes', 'Choose at least one mode', 'कम से कम एक तरीका चुनें', 'కనీసం ఒక విధానం ఎంచుకోండి')
k('blockOverlap', 'Overlaps other hours on this day', 'इस दिन के दूसरे समय से टकराता है', 'ఈ రోజు ఇతర గంటలతో అతివ్యాప్తి చెందుతుంది')
k('saveSchedule', 'Save weekly hours', 'साप्ताहिक समय सहेजें', 'వారపు గంటలు సేవ్ చేయండి')
k('fixProblems', 'Fix the highlighted hours', 'हाइलाइट किए गए समय ठीक करें', 'హైలైట్ చేసిన గంటలను సరిచేయండి')
k('scheduleSaved', 'Schedule saved', 'शेड्यूल सहेजा गया', 'షెడ్యూల్ సేవ్ అయింది')
k('leavesEmpty', 'No leaves planned.', 'कोई छुट्टी तय नहीं।', 'సెలవులు ప్లాన్ చేయలేదు.')
k('addLeave', 'Add leave', 'छुट्टी जोड़ें', 'సెలవు జోడించండి')
k('leaveReason', 'Reason (optional)', 'कारण (वैकल्पिक)', 'కారణం (ఐచ్ఛికం)')
k('leaveAdded', 'Leave added', 'छुट्टी जोड़ी गई', 'సెలవు జోడించబడింది')
k('leaveConflictsTitle', '{count} booked consultations on this day', 'इस दिन {count} बुक परामर्श', 'ఈ రోజు {count} బుక్ అయిన సంప్రదింపులు')
k('leaveConflictsBody', 'They are not cancelled automatically. Please ask the care team to reschedule them.', 'ये अपने-आप रद्द नहीं होते। कृपया केयर टीम से इन्हें फिर से तय करवाएँ।', 'ఇవి ఆటోమేటిక్‌గా రద్దు కావు. దయచేసి వీటిని మళ్లీ షెడ్యూల్ చేయమని కేర్ టీమ్‌ను అడగండి.')
k('earningsTitle', 'Earnings', 'कमाई', 'ఆదాయం')
k('previousMonth', 'Previous month', 'पिछला महीना', 'మునుపటి నెల')
k('nextMonth', 'Next month', 'अगला महीना', 'తదుపరి నెల')
k('earnPayable', 'Payable to you', 'आपको देय', 'మీకు చెల్లించవలసినది')
k('earnServices', '{count} completed consultations', '{count} पूरे परामर्श', '{count} పూర్తయిన సంప్రదింపులు')
k('earnGross', 'Gross', 'कुल', 'స్థూలం')
k('earnPlatformFee', 'Platform fee', 'प्लेटफ़ॉर्म शुल्क', 'ప్లాట్‌ఫామ్ ఫీజు')
k('earnRefunds', 'Refunds', 'रिफ़ंड', 'రీఫండ్‌లు')
k('earnLines', 'Details', 'विवरण', 'వివరాలు')
k('earnEmpty', 'No paid consultations this month.', 'इस महीने कोई भुगतान वाला परामर्श नहीं।', 'ఈ నెల చెల్లించిన సంప్రదింపులు లేవు.')
k('profileTitle', 'Profile', 'प्रोफ़ाइल', 'ప్రొఫైల్')
k('photoGallery', 'Choose photo', 'फ़ोटो चुनें', 'ఫోటో ఎంచుకోండి')
k('photoCamera', 'Take photo', 'फ़ोटो लें', 'ఫోటో తీయండి')
k('photoUpdated', 'Photo updated', 'फ़ोटो अपडेट हुई', 'ఫోటో అప్‌డేట్ అయింది')
k('photoTooLarge', 'The photo must be under 5 MB.', 'फ़ोटो 5 MB से कम होनी चाहिए।', 'ఫోటో 5 MB కంటే తక్కువ ఉండాలి.')
k('regNo', 'Reg. {number}', 'पंजीकरण {number}', 'రిజి. {number}')
k('ratingLine', '★ {rating} ({count} reviews)', '★ {rating} ({count} समीक्षाएँ)', '★ {rating} ({count} సమీక్షలు)')
k('acceptingBookings', 'Accepting new bookings', 'नई बुकिंग ले रहे हैं', 'కొత్త బుకింగ్‌లు స్వీకరిస్తున్నారు')
k('acceptingBookingsHint', 'When off, you are hidden from doctor search.', 'बंद होने पर आप डॉक्टर खोज में नहीं दिखेंगे।', 'ఆఫ్‌లో ఉంటే డాక్టర్ శోధనలో మీరు కనిపించరు.')
k('bookingsOn', 'You are accepting bookings', 'आप बुकिंग ले रहे हैं', 'మీరు బుకింగ్‌లు స్వీకరిస్తున్నారు')
k('bookingsOff', 'Bookings paused', 'बुकिंग रुकी हुई', 'బుకింగ్‌లు నిలిపివేయబడ్డాయి')
k('feesTitle', 'Consultation fees', 'परामर्श शुल्क', 'సంప్రదింపు ఫీజులు')
k('qualifications', 'Qualifications', 'योग्यताएँ', 'అర్హతలు')
k('languagesSpoken', 'Languages spoken', 'बोली जाने वाली भाषाएँ', 'మాట్లాడే భాషలు')
k('bio', 'About you', 'आपके बारे में', 'మీ గురించి')
k('profileSaved', 'Profile saved', 'प्रोफ़ाइल सहेजी गई', 'ప్రొఫైల్ సేవ్ అయింది')
k('languageTitle', 'Language', 'भाषा', 'భాష')
k('logoutConfirmTitle', 'Log out?', 'लॉग आउट करें?', 'లాగ్ అవుట్ చేయాలా?')
k('logoutConfirmBody', 'You will need your phone OTP and authenticator code to sign in again.', 'दोबारा साइन इन करने के लिए फ़ोन OTP और ऑथेंटिकेटर कोड चाहिए होगा।', 'మళ్లీ సైన్ ఇన్ చేయడానికి ఫోన్ OTP, ఆథెంటికేటర్ కోడ్ అవసరం.')


def build():
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, '..', 'lib', 'l10n')
    os.makedirs(out, exist_ok=True)
    keys = [t[0] for t in T]
    dupes = {x for x in keys if keys.count(x) > 1}
    assert not dupes, f'duplicate keys: {dupes}'
    for idx, lang in ((1, 'en'), (2, 'hi'), (3, 'te')):
        arb = {'@@locale': lang}
        for row in T:
            key, text = row[0], row[idx]
            arb[key] = text
            meta = {}
            if key in P:
                meta['placeholders'] = {n: {'type': t} for n, t in P[key].items()}
            if lang != 'en' and key in MED:
                meta['description'] = 'GLOSSARY-REVIEW: clinical term, verify against the approved glossary'
            if meta and (lang == 'en' or 'description' in meta or 'placeholders' in meta):
                arb['@' + key] = meta
        with open(os.path.join(out, f'app_{lang}.arb'), 'w', encoding='utf-8') as f:
            json.dump(arb, f, ensure_ascii=False, indent=2)
            f.write('\n')
    print(f'{len(T)} keys x 3 locales written to lib/l10n')


if __name__ == '__main__':
    build()
