import { randomUUID } from 'node:crypto';
import { desc, eq, inArray } from 'drizzle-orm';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import type { DbOrTx } from '../../db/client.js';
import { careEpisodes, facilities, patients, providers, referrals, specialties } from '../../db/schema.js';
import { assertCanActForPatient, listActablePatients } from '../../lib/access.js';
import { audit } from '../../lib/audit.js';
import { hasRole } from '../../lib/context.js';
import { errors } from '../../lib/errors.js';
import { PLATFORM_NAME, PdfBuilder, pdfDate } from '../../lib/pdf.js';
import { envelope, pageFromQuery } from '../../lib/pagination.js';
import { ageFromDob, istDate, iso } from '../../lib/time.js';
import { parse, zUuid } from '../../lib/validate.js';
import { requireRoles } from '../../plugins/auth.js';
import { addEvent } from '../episodes/service.js';
import { toFacility } from '../providers/routes.js';
import { storeRecord } from '../records/service.js';

/** Contract section 36: referrals with a referral-letter PDF. */
type ReferralRow = typeof referrals.$inferSelect;

const NEXT: Record<string, string[]> = {
  created: ['sent', 'accepted', 'cancelled'],
  sent: ['accepted', 'completed', 'cancelled'],
  accepted: ['completed', 'cancelled'],
  completed: [],
  cancelled: [],
};

export async function toReferrals(db: DbOrTx, rows: ReferralRow[]) {
  if (!rows.length) return [];
  const [facs, pats] = await Promise.all([
    db.select().from(facilities).where(inArray(facilities.id, [...new Set(rows.map((r) => r.facilityId))])),
    db.select({ id: patients.id, name: patients.name }).from(patients).where(inArray(patients.id, [...new Set(rows.map((r) => r.patientId))])),
  ]);
  const fm = new Map(facs.map((f) => [f.id, f]));
  const pm = new Map(pats.map((p) => [p.id, p.name]));
  return rows.map((r) => ({
    id: r.id,
    patientId: r.patientId,
    patientName: pm.get(r.patientId) ?? '',
    careEpisodeId: r.careEpisodeId,
    facility: toFacility(fm.get(r.facilityId)!),
    specialty: r.specialty,
    urgency: r.urgency,
    reason: r.reason,
    status: r.status,
    letterRecordId: r.letterRecordId,
    createdByName: r.createdByName,
    createdAt: iso(r.createdAt),
    updatedAt: iso(r.updatedAt),
  }));
}

export async function renderReferralPdf(p: {
  id: string;
  date: Date;
  doctor: { name: string; qualification: string; registrationNumber: string };
  patient: { name: string; age: number | null; gender: string };
  facility: { name: string; address: string; area: string; city: string; phone: string };
  specialtyName: string | null;
  urgency: string;
  reason: string;
  clinicalSummary: string | null;
}): Promise<Buffer> {
  const ref = `REF-${p.id.slice(0, 8).toUpperCase()}`;
  const date = pdfDate(p.date);
  const b = new PdfBuilder('Referral Letter', `${ref}  |  ${date}`, { author: p.doctor.name, subject: 'Referral' });
  b.infoBoxes([
    {
      title: 'Referred to',
      rows: [
        ['Facility', p.facility.name],
        ['Address', `${p.facility.address}, ${p.facility.area}, ${p.facility.city}`],
        ['Phone', p.facility.phone],
        ['Department', p.specialtyName ?? 'As appropriate'],
      ],
    },
    {
      title: 'Patient',
      rows: [
        ['Name', p.patient.name],
        ['Age / Gender', `${p.patient.age ?? '-'} / ${p.patient.gender}`],
        ['Urgency', p.urgency === 'urgent' ? 'URGENT' : 'Routine'],
        ['Date', date],
      ],
    },
  ]);
  b.heading('Reason for referral');
  b.paragraph(`Dear colleague, I am referring the above patient for your assessment and further management. ${p.reason}`);
  if (p.clinicalSummary) {
    b.heading('Clinical summary');
    b.paragraph(p.clinicalSummary);
  }
  b.heading('Referring doctor');
  b.paragraph(`${p.doctor.name}, ${p.doctor.qualification} (Reg. No. ${p.doctor.registrationNumber})`);
  b.signature([p.doctor.name, `Reg. No. ${p.doctor.registrationNumber}`, 'Digitally generated; no physical signature']);
  return b.finish([`Digitally generated by ${PLATFORM_NAME} on ${date} (${ref}). Please bring this letter and recent reports to the visit.`, 'In an emergency call 108 or go to the nearest emergency department.']);
}

export async function referralRoutes(app: FastifyInstance): Promise<void> {
  const svc = app.svc;
  const db = svc.db;

  app.post('/clinician/referrals', { preHandler: requireRoles(svc, 'doctor') }, async (req, reply) => {
    const body = parse(
      z.object({
        careEpisodeId: zUuid,
        facilityId: zUuid,
        specialty: z.string().trim().max(40).optional(),
        urgency: z.enum(['routine', 'urgent']),
        reason: z.string().trim().min(1).max(2000),
        clinicalSummary: z.string().trim().max(4000).optional(),
      }),
      req.body,
    );
    const [ep] = await db.select().from(careEpisodes).where(eq(careEpisodes.id, body.careEpisodeId));
    if (!ep) throw errors.notFound('Care episode');
    await assertCanActForPatient(db, req.ctx, ep.patientId, 'manage_care', 'referral.create');
    const [fac] = await db.select().from(facilities).where(eq(facilities.id, body.facilityId));
    if (!fac) throw errors.validation('Unknown facilityId', { field: 'facilityId' });
    let specialtyName: string | null = null;
    if (body.specialty) {
      const [sp] = await db.select().from(specialties).where(eq(specialties.code, body.specialty));
      if (!sp) throw errors.validation('Unknown specialty code', { field: 'specialty' });
      specialtyName = sp.name;
    }
    const providerId = req.ctx.user.providerId;
    if (!providerId) throw errors.forbidden('Doctor profile required');
    const [doc] = await db.select().from(providers).where(eq(providers.id, providerId));
    const [pat] = await db.select().from(patients).where(eq(patients.id, ep.patientId));
    const id = randomUUID();
    const now = new Date();
    const pdf = await renderReferralPdf({
      id,
      date: now,
      doctor: doc,
      patient: { name: pat.name ?? 'Patient', age: ageFromDob(pat.dob), gender: pat.gender },
      facility: fac,
      specialtyName,
      urgency: body.urgency,
      reason: body.reason,
      clinicalSummary: body.clinicalSummary ?? null,
    });
    const row = await db.transaction(async (tx) => {
      const rec = await storeRecord(tx, svc.storage, {
        patientId: ep.patientId,
        type: 'other',
        title: `Referral letter - ${fac.name}`,
        recordDate: istDate(now),
        source: 'clinician_verified',
        uploadedByUserId: req.ctx.user.id,
        uploadedByName: doc.name,
        fileName: `referral-${id.slice(0, 8)}.pdf`,
        mimeType: 'application/pdf',
        data: pdf,
      });
      const [r] = await tx
        .insert(referrals)
        .values({
          id,
          patientId: ep.patientId,
          careEpisodeId: ep.id,
          facilityId: fac.id,
          specialty: body.specialty ?? null,
          urgency: body.urgency,
          reason: body.reason,
          clinicalSummary: body.clinicalSummary ?? null,
          letterRecordId: rec.id,
          createdByUserId: req.ctx.user.id,
          createdByName: doc.name,
          doctorId: doc.id,
          createdAt: now,
          updatedAt: now,
        })
        .returning();
      await addEvent(tx, ep.id, 'referral_created', `Referral to ${fac.name} (${body.urgency})`, req.ctx.actor, { referralId: id, recordId: rec.id, facilityId: fac.id });
      await audit(tx, req.ctx.actor, { action: 'referral.create', entityType: 'referral', entityId: id, metadata: { urgency: body.urgency, facilityId: fac.id } });
      return r;
    });
    await svc.notify.notifyPatient(ep.patientId, {
      template: 'referral_created',
      params: { doctor: doc.name },
      category: 'care_plan',
      deepLink: `/referrals/${row.id}`,
      dedupeKey: `referral:${row.id}`,
    });
    return reply.code(201).send((await toReferrals(db, [row]))[0]);
  });

  app.get('/referrals', async (req) => {
    const q = parse(z.object({ patientId: zUuid.optional() }), req.query);
    const page = pageFromQuery(req.query);
    let where;
    if (q.patientId) {
      await assertCanActForPatient(db, req.ctx, q.patientId, ['view_records', 'staff_ops'], 'referral.list');
      where = eq(referrals.patientId, q.patientId);
    } else if (hasRole(req.ctx.user, 'doctor')) {
      where = eq(referrals.createdByUserId, req.ctx.user.id);
    } else {
      const ids = (await listActablePatients(db, req.ctx.user)).filter((p) => p.permissions.includes('view_records')).map((p) => p.patientId);
      if (!ids.length) return { items: [], nextCursor: null };
      where = inArray(referrals.patientId, ids);
    }
    const rows = await db.select().from(referrals).where(where).orderBy(desc(referrals.createdAt)).limit(page.limit + 1).offset(page.offset);
    return envelope(await toReferrals(db, rows), page);
  });

  app.patch('/referrals/:id', async (req) => {
    const { id } = parse(z.object({ id: zUuid }), req.params);
    const body = parse(z.object({ status: z.enum(['sent', 'accepted', 'completed', 'cancelled']), note: z.string().trim().max(1000).optional() }), req.body);
    const [r] = await db.select().from(referrals).where(eq(referrals.id, id));
    if (!r) throw errors.notFound('Referral');
    const isCreator = r.createdByUserId === req.ctx.user.id;
    const isOps = hasRole(req.ctx.user, 'coordinator', 'ops_admin', 'super_admin');
    if (!isCreator && !isOps) {
      await audit(db, req.ctx.actor, { action: 'referral.update', entityType: 'referral', entityId: id, outcome: 'denied' });
      throw errors.forbidden();
    }
    if (!(NEXT[r.status] ?? []).includes(body.status)) throw errors.invalidTransition(r.status, body.status);
    const row = await db.transaction(async (tx) => {
      const [u] = await tx.update(referrals).set({ status: body.status, updatedAt: new Date() }).where(eq(referrals.id, id)).returning();
      await addEvent(tx, r.careEpisodeId, 'referral_updated', `Referral ${body.status}`, req.ctx.actor, { referralId: id, status: body.status, ...(body.note ? { note: body.note } : {}) });
      await audit(tx, req.ctx.actor, { action: 'referral.update', entityType: 'referral', entityId: id, metadata: { from: r.status, to: body.status } });
      return u;
    });
    return (await toReferrals(db, [row]))[0];
  });
}
