import { randomUUID } from 'node:crypto';
import type { DbOrTx } from '../../db/client.js';
import { medications, prescriptions, type appointments, type patients, type providers, type RxItemJson, type RxWarningJson } from '../../db/schema.js';
import type { Actor } from '../../lib/context.js';
import { addDays, ageFromDob, istDate, iso } from '../../lib/time.js';
import { addEvent } from '../episodes/service.js';
import { storeRecord } from '../records/service.js';
import type { StorageAdapter } from '../records/storage.js';
import { PLATFORM_NAME, PdfBuilder, pdfDate } from '../../lib/pdf.js';

export type PrescriptionRow = typeof prescriptions.$inferSelect;

export const toPrescription = (p: PrescriptionRow) => ({
  id: p.id,
  patientId: p.patientId,
  patientName: p.patientName,
  patientAge: p.patientAge,
  patientGender: p.patientGender,
  doctorId: p.doctorId,
  doctorName: p.doctorName,
  doctorQualifications: p.doctorQualifications,
  doctorRegistration: p.doctorRegistration,
  appointmentId: p.appointmentId,
  careEpisodeId: p.careEpisodeId,
  clinicalNote: p.clinicalNote,
  items: p.items,
  advice: p.advice,
  followUpInDays: p.followUpInDays,
  recordId: p.recordId,
  warnings: p.warnings ?? [],
  createdAt: iso(p.createdAt),
});

const cap = (s: string) => (s ? s[0].toUpperCase() + s.slice(1) : s);

/**
 * e-Prescription PDF (contract section 31). Minimum necessary data: doctor identity, patient name/age/gender,
 * date, items and advice. The clinical note is NOT printed.
 */
export async function renderPrescriptionPdf(p: {
  id: string;
  createdAt: Date;
  doctorName: string;
  doctorQualifications: string;
  doctorRegistration: string;
  patientName: string;
  patientAge: number | null;
  patientGender: string;
  items: RxItemJson[];
  advice: string | null;
  followUpInDays: number | null;
}): Promise<Buffer> {
  const rxNo = `RX-${p.id.slice(0, 8).toUpperCase()}`;
  const date = pdfDate(p.createdAt);
  const b = new PdfBuilder('e-Prescription', `${rxNo}  |  ${date}`, { author: p.doctorName, subject: 'Prescription' });
  b.infoBoxes([
    {
      title: 'Prescribing doctor',
      rows: [
        ['Name', p.doctorName],
        ['Qualifications', p.doctorQualifications],
        ['Reg. No.', p.doctorRegistration],
      ],
    },
    {
      title: 'Patient',
      rows: [
        ['Name', p.patientName],
        ['Age / Gender', `${p.patientAge ?? '-'} / ${cap(p.patientGender)}`],
        ['Date', date],
      ],
    },
  ]);
  b.heading('Rx');
  b.table(
    [
      { header: '#', width: 18 },
      { header: 'Medicine', width: 130 },
      { header: 'Dose', width: 62 },
      { header: 'Frequency', width: 78 },
      { header: 'When', width: 64 },
      { header: 'Duration', width: 52 },
      { header: 'Instructions', width: 112 },
    ],
    p.items.map((it, i) => [
      String(i + 1),
      `${it.drugName}${it.strength ? ` ${it.strength}` : ''}\n${cap(it.form)}`,
      it.dose,
      it.frequency,
      [it.timing, it.times.length ? it.times.join(', ') : ''].filter(Boolean).join('\n') || '-',
      `${it.durationDays} day${it.durationDays === 1 ? '' : 's'}`,
      it.instructions ?? '-',
    ]),
  );
  if (p.advice) {
    b.heading('Advice');
    b.paragraph(p.advice);
  }
  if (p.followUpInDays) {
    b.heading('Follow-up');
    b.paragraph(`Please follow up in ${p.followUpInDays} day${p.followUpInDays === 1 ? '' : 's'}, or earlier if symptoms worsen.`);
  }
  b.signature([p.doctorName, `Reg. No. ${p.doctorRegistration}`, 'Digitally generated; no physical signature', '[REQUIRES LEGAL REVIEW: e-signature rules]']);
  return b.finish([
    `Digitally generated by ${PLATFORM_NAME} on ${date} from a teleconsultation record (${rxNo}).`,
    'Valid only with the prescribing doctor details above. In an emergency call 108.',
  ]);
}

/** Case-insensitive name/strength match of a prescription item against pharmacy catalogue names. */
export function matchProduct<T extends { name: string; inStock: boolean }>(item: RxItemJson, catalogue: T[]): T | null {
  const norm = (s: string) => s.toLowerCase().replace(/\s+/g, '');
  const drug = norm(item.drugName);
  const strength = item.strength ? norm(item.strength) : null;
  const byName = catalogue.filter((p) => norm(p.name).includes(drug));
  const exact = strength ? byName.filter((p) => norm(p.name).includes(strength)) : byName;
  const pick = (list: T[]) => list.find((p) => p.inStock) ?? list[0] ?? null;
  return strength ? pick(exact) : pick(byName);
}

// ---------------------------------------------------------------- issuing (shared by the API and the dev seed)

export interface PrescriptionInput {
  clinicalNote?: string | null;
  items: RxItemJson[];
  advice?: string | null;
  followUpInDays?: number | null;
}

/**
 * Create the prescription: PDF -> `prescription` MedicalRecord (clinician_verified), one Medication per item
 * (so reminders start), an episode event. Runs inside the caller's transaction.
 */
export async function issuePrescription(
  tx: DbOrTx,
  storage: StorageAdapter,
  p: {
    appointment: typeof appointments.$inferSelect;
    doctor: typeof providers.$inferSelect;
    doctorUserId: string;
    patient: typeof patients.$inferSelect;
    input: PrescriptionInput;
    actor: Actor;
    now?: Date;
    warnings?: RxWarningJson[];
    overrideReason?: string | null;
  },
): Promise<PrescriptionRow> {
  const now = p.now ?? new Date();
  const id = randomUUID();
  const snapshot = {
    patientName: p.patient.name ?? 'Patient',
    patientAge: ageFromDob(p.patient.dob, now),
    patientGender: p.patient.gender,
    doctorName: p.doctor.name,
    doctorQualifications: p.doctor.qualification,
    doctorRegistration: p.doctor.registrationNumber,
  };
  const pdf = await renderPrescriptionPdf({
    id,
    createdAt: now,
    ...snapshot,
    items: p.input.items,
    advice: p.input.advice ?? null,
    followUpInDays: p.input.followUpInDays ?? null,
  });
  const today = istDate(now);
  const record = await storeRecord(tx, storage, {
    patientId: p.patient.id,
    type: 'prescription',
    title: `e-Prescription - ${p.doctor.name}`,
    recordDate: today,
    source: 'clinician_verified',
    uploadedByUserId: p.doctorUserId,
    uploadedByName: p.doctor.name,
    fileName: `prescription-${id.slice(0, 8)}.pdf`,
    mimeType: 'application/pdf',
    data: pdf,
  });
  const [row] = await tx
    .insert(prescriptions)
    .values({
      id,
      patientId: p.patient.id,
      doctorId: p.doctor.id,
      appointmentId: p.appointment.id,
      careEpisodeId: p.appointment.careEpisodeId,
      ...snapshot,
      clinicalNote: p.input.clinicalNote ?? null,
      items: p.input.items,
      advice: p.input.advice ?? null,
      followUpInDays: p.input.followUpInDays ?? null,
      recordId: record.id,
      warnings: p.warnings ?? [],
      overrideReason: p.overrideReason ?? null,
      createdByUserId: p.doctorUserId,
      createdAt: now,
    })
    .returning();
  for (const it of p.input.items) {
    await tx.insert(medications).values({
      patientId: p.patient.id,
      name: `${it.drugName}${it.strength ? ` ${it.strength}` : ''}`.slice(0, 100),
      dose: it.dose.slice(0, 60),
      frequency: it.frequency.slice(0, 60),
      times: it.times,
      startDate: today,
      endDate: addDays(today, Math.max(1, it.durationDays) - 1),
      instructions: [it.timing, it.instructions].filter(Boolean).join('; ').slice(0, 500) || null,
      source: 'clinician_verified',
      prescribedByName: p.doctor.name,
      prescriptionId: id,
      createdAt: now,
    });
  }
  await addEvent(tx, p.appointment.careEpisodeId, 'prescription_issued', `e-Prescription issued by ${p.doctor.name}`, p.actor, {
    prescriptionId: id,
    recordId: record.id,
    appointmentId: p.appointment.id,
    itemCount: p.input.items.length,
  });
  return row;
}
