# v1.3 strings (API_CONTRACT §41–§61). Imported by gen_arb.py, which owns
# the build; keep the same (key, en, hi, te, med) shape.


def register(k, P, MED):
    P.update({
        'calorieTarget': {'kcal': 'int'}, 'cashlessIntro': {'insurer': 'String'},
        'checkinDoneAt': {'time': 'String'}, 'checkinFamilyDone': {'name': 'String', 'time': 'String'},
        'checkinFamilyMissed': {'name': 'String'}, 'checkinFamilyPending': {'name': 'String', 'window': 'String'},
        'checkinHistorySemantic': {'ok': 'int', 'late': 'int', 'missed': 'int'}, 'checkinIntro': {'name': 'String'},
        'checkinWindow': {'start': 'String', 'end': 'String'},
        'checkoutSummarySemantic': {'subtotal': 'String', 'discount': 'String', 'wallet': 'String', 'payable': 'String'},
        'companyPlanActivated': {'name': 'String'}, 'copyCommand': {'command': 'String'},
        'couponApplied': {'code': 'String'}, 'dietAdherenceSemantic': {'pct': 'int'},
        'fastingHoursShort': {'hours': 'int'}, 'fastingNoticeBody': {'hours': 'int'},
        'finishSession': {'done': 'int', 'total': 'int'}, 'gpsLocation': {'lat': 'String', 'lng': 'String'},
        'handledBy': {'name': 'String'}, 'holdSeconds': {'seconds': 'int'},
        'labCartBar': {'count': 'int', 'amount': 'String'}, 'lastDoneOn': {'date': 'String'},
        'lastReadingAt': {'time': 'String'}, 'locationUpdatedAt': {'time': 'String'}, 'logoOf': {'name': 'String'},
        'markExerciseDone': {'name': 'String'}, 'metersValue': {'meters': 'int'}, 'minutesCount': {'minutes': 'int'},
        'openAlerts': {'count': 'int'}, 'opinionBy': {'name': 'String'}, 'opinionWithinHours': {'hours': 'int'},
        'painScoreValue': {'score': 'int'}, 'painTrendSemantic': {'score': 'int'}, 'planBy': {'name': 'String'},
        'planDates': {'start': 'String', 'end': 'String'}, 'policyNumberKeep': {'masked': 'String'},
        'questionTooShort': {'count': 'int'}, 'readingsDueToday': {'count': 'int'},
        'readingsReceived': {'received': 'int', 'expected': 'int'}, 'recordsImported': {'count': 'int'},
        'removeFromCart': {'name': 'String'}, 'repeatsEveryMonths': {'months': 'int'},
        'reportInHours': {'hours': 'int'}, 'resultsFor': {'query': 'String'}, 'safeZoneIntro': {'name': 'String'},
        'safeZoneSub': {'name': 'String'}, 'secondOpinionConsent': {'count': 'int'},
        'sessionsDone': {'done': 'int', 'planned': 'int'}, 'setsReps': {'sets': 'int', 'reps': 'int'},
        'sponsoredBy': {'name': 'String'}, 'sumInsuredValue': {'amount': 'String'}, 'testsIncluded': {'count': 'int'},
        'ticketCreated': {'number': 'String'},
        'trendSemantic': {'type': 'String', 'count': 'int', 'latest': 'String', 'date': 'String'},
        'updatedAt': {'time': 'String'}, 'validUntil': {'date': 'String'}, 'walletAvailable': {'amount': 'String'},
        'walletBalanceSemantic': {'amount': 'String'}, 'whenWasItDone': {'name': 'String'}, 'youRated': {'score': 'int'},
        'youSaveVsMrp': {'amount': 'String'},
    })

    # ------------------------------------------------------------ Shared
    k('more', 'More', 'और', 'మరిన్ని')
    k('moreServices', 'More services', 'और सेवाएँ', 'మరిన్ని సేవలు')
    k('apply', 'Apply', 'लागू करें', 'వర్తింపజేయండి')
    k('done', 'Done', 'हो गया', 'పూర్తయింది')
    k('from', 'From', 'से', 'నుండి')
    k('to', 'To', 'तक', 'వరకు')
    k('refresh', 'Refresh', 'रीफ़्रेश करें', 'రిఫ్రెష్ చేయండి')
    k('restart', 'Restart', 'फिर से शुरू करें', 'మళ్లీ ప్రారంభించండి')
    k('redeem', 'Redeem', 'रिडीम करें', 'రిడీమ్ చేయండి')
    k('copied', 'Copied', 'कॉपी हो गया', 'కాపీ అయింది')
    k('copyCode', 'Copy code', 'कोड कॉपी करें', 'కోడ్ కాపీ చేయండి')
    k('copyCommand', 'Copy {command}', '{command} कॉपी करें', '{command} కాపీ చేయండి')
    k('notSet', 'Not set', 'सेट नहीं है', 'సెట్ చేయలేదు')
    k('expired', 'Expired', 'समाप्त', 'గడువు ముగిసింది')
    k('provider', 'Provider', 'प्रदाता', 'ప్రొవైడర్')
    k('subject', 'Subject', 'विषय', 'విషయం')
    k('credit', 'Credit', 'जमा', 'జమ')
    k('debit', 'Debit', 'नामे', 'డెబిట్')
    k('updatedAt', 'Updated {time}', '{time} को अपडेट हुआ', '{time}కి అప్‌డేట్ అయింది')
    k('validUntil', 'Valid until {date}', '{date} तक मान्य', '{date} వరకు చెల్లుతుంది')
    k('planBy', 'Plan by {name}', '{name} द्वारा योजना', '{name} రూపొందించిన ప్లాన్')
    k('planDates', '{start} – {end}', '{start} – {end}', '{start} – {end}')
    k('reasonOptional', 'Reason (optional)', 'कारण (वैकल्पिक)', 'కారణం (ఐచ్ఛికం)')
    k('logoOf', '{name} logo', '{name} का लोगो', '{name} లోగో')
    k('poweredByCareCompanion', 'Powered by CareCompanion', 'केयरकम्पैनियन द्वारा संचालित', 'కేర్‌కంపానియన్ ఆధారితం')
    k('adherence', 'Adherence', 'पालन', 'పాటింపు', MED)

    # Quick access tiles
    k('qxLabTests', 'Lab Tests', 'लैब टेस्ट', 'ల్యాబ్ పరీక్షలు', MED)
    k('qxCarePrograms', 'Care Programs', 'केयर प्रोग्राम', 'కేర్ ప్రోగ్రామ్‌లు')
    k('qxPreventiveCare', 'Preventive Care', 'निवारक देखभाल', 'నివారణ సంరక్షణ', MED)
    k('qxSecondOpinion', 'Second Opinion', 'दूसरी राय', 'రెండో అభిప్రాయం', MED)
    k('qxInsurance', 'Insurance', 'बीमा', 'బీమా')
    k('qxExercise', 'Exercise', 'व्यायाम', 'వ్యాయామం')
    k('qxDiet', 'Diet', 'आहार', 'ఆహారం')

    # ------------------------------------------------------------ §41 Check-in
    k('dailyCheckin', 'Daily check-in', 'दैनिक चेक-इन', 'రోజువారీ చెక్-ఇన్')
    k('dailyCheckinSub', 'An "I\'m OK" tap each morning', 'हर सुबह "मैं ठीक हूँ" पर टैप', 'ప్రతి ఉదయం "నేను బాగున్నాను" ట్యాప్')
    k('imOkToday', "I'm OK today", 'मैं आज ठीक हूँ', 'నేను ఈరోజు బాగున్నాను')
    k('checkinPrompt', 'One tap lets your family know you are fine today.', 'एक टैप से आपके परिवार को पता चलेगा कि आप आज ठीक हैं।', 'ఒక్క ట్యాప్‌తో మీరు ఈరోజు బాగున్నారని మీ కుటుంబానికి తెలుస్తుంది.')
    k('checkinMissedBody', "Today's check-in window has passed. Checking in now still tells your family you're OK.", 'आज की चेक-इन अवधि बीत गई है। अभी चेक-इन करने से भी परिवार को पता चलेगा कि आप ठीक हैं।', 'ఈరోజు చెక్-ఇన్ సమయం దాటింది. ఇప్పుడు చెక్-ఇన్ చేసినా మీరు బాగున్నారని కుటుంబానికి తెలుస్తుంది.')
    k('checkinMoodOptional', 'How are you feeling? (optional)', 'आप कैसा महसूस कर रहे हैं? (वैकल्पिक)', 'మీరు ఎలా ఉన్నారు? (ఐచ్ఛికం)')
    k('checkinWindow', '{start}–{end}', '{start}–{end}', '{start}–{end}')
    k('checkinThanks', 'Thank you! Your family has been told you are OK.', 'धन्यवाद! आपके परिवार को बता दिया गया है कि आप ठीक हैं।', 'ధన్యవాదాలు! మీరు బాగున్నారని కుటుంబానికి తెలియజేశాం.')
    k('checkinDoneAt', 'Checked in at {time}', '{time} पर चेक-इन किया', '{time}కి చెక్-ఇన్ చేశారు')
    k('checkinFamilyDone', '{name} checked in today at {time}', '{name} ने आज {time} पर चेक-इन किया', '{name} ఈరోజు {time}కి చెక్-ఇన్ చేశారు')
    k('checkinFamilyMissed', "{name} hasn't checked in today", '{name} ने आज चेक-इन नहीं किया', '{name} ఈరోజు చెక్-ఇన్ చేయలేదు')
    k('checkinFamilyPending', '{name} has not checked in yet (window {window})', '{name} ने अभी चेक-इन नहीं किया (समय {window})', '{name} ఇంకా చెక్-ఇన్ చేయలేదు (సమయం {window})')
    k('checkinOk', 'On time', 'समय पर', 'సమయానికి')
    k('checkinLate', 'Late', 'देर से', 'ఆలస్యంగా')
    k('checkinMissed', 'Missed', 'छूट गया', 'మిస్ అయింది')
    k('checkinPending', 'Pending', 'बाकी', 'పెండింగ్')
    k('checkinHistorySemantic', 'Last 30 days: {ok} on time, {late} late, {missed} missed', 'पिछले 30 दिन: {ok} समय पर, {late} देर से, {missed} छूटे', 'గత 30 రోజులు: {ok} సమయానికి, {late} ఆలస్యం, {missed} మిస్')
    k('checkinIntro', "A daily \"I'm OK\" check-in for {name}. If it is missed, family and the care coordinator are alerted.", '{name} के लिए रोज़ "मैं ठीक हूँ" चेक-इन। छूटने पर परिवार और केयर कोऑर्डिनेटर को सूचना मिलती है।', '{name} కోసం రోజువారీ "నేను బాగున్నాను" చెక్-ఇన్. మిస్ అయితే కుటుంబానికి, కేర్ కోఆర్డినేటర్‌కు హెచ్చరిక వెళ్తుంది.')
    k('checkinNoPermission', 'Only family members with "Manage care" permission can change this.', 'केवल "देखभाल प्रबंधन" अनुमति वाले परिवारजन इसे बदल सकते हैं।', '"సంరక్షణ నిర్వహణ" అనుమతి ఉన్న కుటుంబ సభ్యులు మాత్రమే దీన్ని మార్చగలరు.')
    k('checkinEnable', 'Daily check-in', 'दैनिक चेक-इन', 'రోజువారీ చెక్-ఇన్')
    k('checkinEnableSub', 'Show the "I\'m OK today" card every morning', 'हर सुबह "मैं आज ठीक हूँ" कार्ड दिखाएँ', 'ప్రతి ఉదయం "నేను ఈరోజు బాగున్నాను" కార్డ్ చూపించండి')
    k('checkinWindowStart', 'Window opens', 'समय शुरू', 'సమయం ప్రారంభం')
    k('checkinWindowEnd', 'Window closes', 'समय समाप्त', 'సమయం ముగింపు')
    k('checkinWindowInvalid', 'The window must end after it starts', 'समाप्ति का समय शुरुआत के बाद होना चाहिए', 'ముగింపు సమయం ప్రారంభం తర్వాత ఉండాలి')
    k('checkinEscalateAfter', 'Alert the care team after', 'इतनी देर बाद केयर टीम को सूचित करें', 'ఇంత సమయం తర్వాత కేర్ టీమ్‌కు హెచ్చరిక')
    k('minutesCount', '{minutes} minutes', '{minutes} मिनट', '{minutes} నిమిషాలు')
    k('checkinNotifyFamily', 'Notify family if missed', 'छूटने पर परिवार को सूचित करें', 'మిస్ అయితే కుటుంబానికి తెలియజేయండి')
    k('checkinNotifyCoordinator', 'Notify the care coordinator', 'केयर कोऑर्डिनेटर को सूचित करें', 'కేర్ కోఆర్డినేటర్‌కు తెలియజేయండి')
    k('checkinHowItWorks', 'If there is no check-in by the end of the window, family get a notification. If it is still missing after the set time, the care coordinator follows up. Times are in IST.', 'समय समाप्त होने तक चेक-इन न होने पर परिवार को सूचना मिलती है। तय समय के बाद भी न होने पर केयर कोऑर्डिनेटर संपर्क करते हैं। समय IST में है।', 'సమయం ముగిసే వరకు చెక్-ఇన్ లేకపోతే కుటుంబానికి నోటిఫికేషన్ వస్తుంది. నిర్ణీత సమయం తర్వాత కూడా లేకపోతే కేర్ కోఆర్డినేటర్ సంప్రదిస్తారు. సమయాలు IST లో ఉంటాయి.')
    k('checkinLast30Days', 'Last 30 days', 'पिछले 30 दिन', 'గత 30 రోజులు')
    k('checkinNoHistory', 'No check-ins yet', 'अभी कोई चेक-इन नहीं', 'ఇంకా చెక్-ఇన్‌లు లేవు')

    # ------------------------------------------------------------ §42 Programs
    k('carePrograms', 'Care programs', 'केयर प्रोग्राम', 'కేర్ ప్రోగ్రామ్‌లు')
    k('myPrograms', 'My programs', 'मेरे प्रोग्राम', 'నా ప్రోగ్రామ్‌లు')
    k('programsIntro', 'Your doctor set these up to watch your readings between visits.', 'आपके डॉक्टर ने विज़िट के बीच आपकी रीडिंग देखने के लिए इन्हें शुरू किया है।', 'సందర్శనల మధ్య మీ రీడింగ్‌లను గమనించేందుకు మీ డాక్టర్ వీటిని ఏర్పాటు చేశారు.')
    k('noProgramsTitle', 'No care programs yet', 'अभी कोई केयर प्रोग्राम नहीं', 'ఇంకా కేర్ ప్రోగ్రామ్‌లు లేవు')
    k('noProgramsBody', 'Your doctor can enrol you in a BP, diabetes or heart-care program.', 'आपके डॉक्टर आपको बीपी, डायबिटीज़ या हृदय देखभाल प्रोग्राम में जोड़ सकते हैं।', 'మీ డాక్టర్ మిమ్మల్ని బీపీ, షుగర్ లేదా గుండె సంరక్షణ ప్రోగ్రామ్‌లో చేర్చగలరు.', MED)
    k('logReading', 'Log reading', 'रीडिंग दर्ज करें', 'రీడింగ్ నమోదు చేయండి')
    k('lastReadingAt', 'Last reading {time}', 'पिछली रीडिंग {time}', 'చివరి రీడింగ్ {time}')
    k('adherence7d', 'Readings taken (7 days)', 'ली गई रीडिंग (7 दिन)', 'తీసుకున్న రీడింగ్‌లు (7 రోజులు)')
    k('adherence30d', 'Readings taken (30 days)', 'ली गई रीडिंग (30 दिन)', 'తీసుకున్న రీడింగ్‌లు (30 రోజులు)')
    k('readingsDueToday', '{count} readings due today', 'आज {count} रीडिंग बाकी', 'ఈరోజు {count} రీడింగ్‌లు మిగిలాయి')
    k('readingsDoneToday', "Today's readings done", 'आज की रीडिंग पूरी', 'ఈరోజు రీడింగ్‌లు పూర్తయ్యాయి')
    k('readingsReceived', '{received} of {expected} readings', '{expected} में से {received} रीडिंग', '{expected}లో {received} రీడింగ్‌లు')
    k('openAlerts', '{count} open alerts', '{count} खुली चेतावनियाँ', '{count} తెరిచి ఉన్న హెచ్చరికలు')
    k('openAlertsTitle', 'Alerts', 'चेतावनियाँ', 'హెచ్చరికలు')
    k('noAlerts', 'No alerts in the last 30 days.', 'पिछले 30 दिनों में कोई चेतावनी नहीं।', 'గత 30 రోజుల్లో హెచ్చరికలు లేవు.')
    k('programPaused', 'Paused', 'रोका गया', 'నిలిపివేయబడింది')
    k('programCompleted', 'Completed', 'पूरा', 'పూర్తయింది')
    k('trend', 'Trend', 'रुझान', 'ధోరణి')
    k('noReadingsYet', 'No readings yet', 'अभी कोई रीडिंग नहीं', 'ఇంకా రీడింగ్‌లు లేవు')
    k('trendSemantic', '{type} trend: {count} days, latest average {latest} on {date}', '{type} रुझान: {count} दिन, नवीनतम औसत {latest} ({date})', '{type} ధోరణి: {count} రోజులు, తాజా సగటు {latest} ({date})')
    k('weeklyReports', 'Weekly reports', 'साप्ताहिक रिपोर्ट', 'వారపు నివేదికలు')
    k('noWeeklyReports', 'Your first weekly report arrives on Monday.', 'आपकी पहली साप्ताहिक रिपोर्ट सोमवार को आएगी।', 'మీ మొదటి వారపు నివేదిక సోమవారం వస్తుంది.')
    k('programDisclaimer', 'Alerts go to your care team. If you feel unwell, call your doctor or 108 in an emergency.', 'चेतावनियाँ आपकी केयर टीम को जाती हैं। तबीयत ठीक न लगे तो डॉक्टर को, आपात स्थिति में 108 पर कॉल करें।', 'హెచ్చరికలు మీ కేర్ టీమ్‌కు వెళ్తాయి. ఆరోగ్యం బాగోలేకపోతే డాక్టర్‌కు, అత్యవసరంలో 108కి కాల్ చేయండి.', MED)
    k('bloodPressure', 'Blood pressure', 'रक्तचाप', 'రక్తపోటు', MED)
    k('bloodPressureShort', 'BP', 'बीपी', 'బీపీ', MED)
    k('glucoseShort', 'Sugar', 'शुगर', 'షుగర్', MED)
    k('weightShort', 'Weight', 'वज़न', 'బరువు')
    k('readingOutOfRange', 'That value looks unusual. Please check and re-enter.', 'यह मान असामान्य लगता है। कृपया जाँचकर फिर दर्ज करें।', 'ఈ విలువ అసాధారణంగా ఉంది. దయచేసి సరిచూసి మళ్లీ నమోదు చేయండి.')
    k('readingSystolicBelowDiastolic', 'The upper (systolic) number must be higher than the lower one.', 'ऊपरी (सिस्टोलिक) संख्या निचली से अधिक होनी चाहिए।', 'పై (సిస్టోలిక్) సంఖ్య కింది సంఖ్య కంటే ఎక్కువగా ఉండాలి.', MED)
    k('readingSafetyNote', 'Readings are shared with your care team. Feeling unwell? Call 108 in an emergency.', 'रीडिंग आपकी केयर टीम के साथ साझा होती हैं। तबीयत ख़राब हो तो आपात स्थिति में 108 पर कॉल करें।', 'రీడింగ్‌లు మీ కేర్ టీమ్‌తో పంచుకోబడతాయి. బాగోలేకపోతే అత్యవసరంలో 108కి కాల్ చేయండి.')
    k('readingSaved', 'Reading saved', 'रीडिंग सहेजी गई', 'రీడింగ్ సేవ్ అయింది')

    # ------------------------------------------------------------ §43 WhatsApp
    k('whatsappAssistant', 'WhatsApp assistant', 'व्हाट्सऐप सहायक', 'వాట్సాప్ సహాయకుడు')
    k('whatsappExplain', 'Get reminders on WhatsApp and reply to check in, log BP or sugar, or ask a question. No diagnosis is given.', 'व्हाट्सऐप पर रिमाइंडर पाएँ और जवाब देकर चेक-इन करें, बीपी या शुगर दर्ज करें या सवाल पूछें। कोई निदान नहीं दिया जाता।', 'వాట్సాప్‌లో రిమైండర్లు పొందండి, జవాబిచ్చి చెక్-ఇన్ చేయండి, బీపీ లేదా షుగర్ నమోదు చేయండి లేదా ప్రశ్న అడగండి. నిర్ధారణ ఇవ్వబడదు.')
    k('whatsappOptIn', 'Use the WhatsApp assistant', 'व्हाट्सऐप सहायक का उपयोग करें', 'వాట్సాప్ సహాయకుడిని ఉపయోగించండి')
    k('whatsappPrivacyNote', 'Messages go to your registered number. Send STOP at any time to opt out.', 'संदेश आपके पंजीकृत नंबर पर जाते हैं। कभी भी बंद करने के लिए STOP भेजें।', 'సందేశాలు మీ నమోదైన నంబర్‌కు వస్తాయి. ఎప్పుడైనా ఆపడానికి STOP పంపండి.')
    k('whatsappTryIt', 'Try it', 'आज़माएँ', 'ప్రయత్నించండి')
    k('whatsappTryIntro', 'Send these messages to our WhatsApp number:', 'ये संदेश हमारे व्हाट्सऐप नंबर पर भेजें:', 'ఈ సందేశాలను మా వాట్సాప్ నంబర్‌కు పంపండి:')
    k('whatsappOptedIn', 'WhatsApp assistant turned on', 'व्हाट्सऐप सहायक चालू हुआ', 'వాట్సాప్ సహాయకుడు ఆన్ అయింది')
    k('whatsappOptedOut', 'WhatsApp assistant turned off', 'व्हाट्सऐप सहायक बंद हुआ', 'వాట్సాప్ సహాయకుడు ఆఫ్ అయింది')
    k('waCmdToday', "Today's medicine and visit reminders", 'आज की दवा और विज़िट के रिमाइंडर', 'ఈరోజు మందులు, సందర్శన రిమైండర్లు')
    k('waCmdCheckin', 'Daily "I\'m OK" check-in', 'दैनिक "मैं ठीक हूँ" चेक-इन', 'రోజువారీ "నేను బాగున్నాను" చెక్-ఇన్')
    k('waCmdBp', 'Record a blood pressure reading', 'रक्तचाप रीडिंग दर्ज करें', 'రక్తపోటు రీడింగ్ నమోదు', MED)
    k('waCmdSugar', 'Record a blood sugar reading', 'ब्लड शुगर रीडिंग दर्ज करें', 'షుగర్ రీడింగ్ నమోదు', MED)
    k('waCmdBook', 'Get links to book care', 'देखभाल बुक करने के लिंक पाएँ', 'సంరక్షణ బుక్ చేసే లింక్‌లు పొందండి')
    k('waCmdStop', 'Stop WhatsApp messages', 'व्हाट्सऐप संदेश बंद करें', 'వాట్సాప్ సందేశాలు ఆపండి')
    k('waCmdStart', 'Start them again', 'फिर से शुरू करें', 'మళ్లీ ప్రారంభించండి')
    k('whatsappNoDiagnosis', 'Replies are general guidance, not a diagnosis. In an emergency call 108.', 'जवाब सामान्य मार्गदर्शन हैं, निदान नहीं। आपात स्थिति में 108 पर कॉल करें।', 'జవాబులు సాధారణ మార్గదర్శకం, నిర్ధారణ కాదు. అత్యవసరంలో 108కి కాల్ చేయండి.')

    # ------------------------------------------------------------ §44 Lab
    k('labTests', 'Lab tests at home', 'घर पर लैब टेस्ट', 'ఇంటి వద్ద ల్యాబ్ పరీక్షలు', MED)
    k('labIntro', 'A trained technician collects the sample at home. Reports come to your records.', 'प्रशिक्षित तकनीशियन घर पर सैंपल लेते हैं। रिपोर्ट आपके रिकॉर्ड में आती है।', 'శిక్షణ పొందిన టెక్నీషియన్ ఇంటి వద్దే శాంపిల్ తీసుకుంటారు. నివేదికలు మీ రికార్డులకు వస్తాయి.')
    k('searchLabTests', 'Search tests (e.g. HbA1c, lipid)', 'टेस्ट खोजें (जैसे HbA1c, लिपिड)', 'పరీక్షలు వెతకండి (ఉదా. HbA1c, లిపిడ్)', MED)
    k('healthPackages', 'Health packages', 'हेल्थ पैकेज', 'ఆరోగ్య ప్యాకేజీలు')
    k('noPackages', 'No packages right now', 'अभी कोई पैकेज नहीं', 'ప్రస్తుతం ప్యాకేజీలు లేవు')
    k('allTests', 'All tests', 'सभी टेस्ट', 'అన్ని పరీక్షలు')
    k('resultsFor', 'Results for "{query}"', '"{query}" के परिणाम', '"{query}" ఫలితాలు')
    k('noLabTests', 'No tests found', 'कोई टेस्ट नहीं मिला', 'పరీక్షలు కనబడలేదు')
    k('labPricingNote', 'Prices are indicative and confirmed at booking.', 'कीमतें सांकेतिक हैं और बुकिंग पर पुष्ट होती हैं।', 'ధరలు సూచనాత్మకం, బుకింగ్ సమయంలో నిర్ధారించబడతాయి.')
    k('testsIncluded', '{count} tests', '{count} टेस्ट', '{count} పరీక్షలు')
    k('fastingRequired', 'Fasting', 'उपवास', 'ఉపవాసం', MED)
    k('fastingHoursShort', 'Fasting {hours} h', '{hours} घंटे उपवास', '{hours} గం. ఉపవాసం', MED)
    k('reportInHours', 'Report in {hours} h', '{hours} घंटे में रिपोर्ट', '{hours} గం.లో నివేదిక')
    k('includedInPackage', 'In package', 'पैकेज में शामिल', 'ప్యాకేజీలో ఉంది')
    k('removeFromCart', 'Remove {name}', '{name} हटाएँ', '{name} తీసివేయండి')
    k('labCartBar', '{count} selected · {amount} · View cart', '{count} चुने · {amount} · कार्ट देखें', '{count} ఎంచుకున్నారు · {amount} · కార్ట్ చూడండి')
    k('sampleBlood', 'Blood', 'रक्त', 'రక్తం', MED)
    k('sampleUrine', 'Urine', 'मूत्र', 'మూత్రం', MED)
    k('sampleSwab', 'Swab', 'स्वैब', 'స్వాబ్', MED)
    k('sampleOther', 'Other sample', 'अन्य सैंपल', 'ఇతర శాంపిల్', MED)
    k('fastingNoticeTitle', 'Fasting needed', 'उपवास आवश्यक', 'ఉపవాసం అవసరం', MED)
    k('fastingNoticeBody', 'Please do not eat for {hours} hours before the sample is collected. Water is fine. Take regular medicines unless your doctor said otherwise.', 'सैंपल लेने से {hours} घंटे पहले कुछ न खाएँ। पानी पी सकते हैं। डॉक्टर ने मना न किया हो तो नियमित दवाएँ लें।', 'శాంపిల్ తీసుకునే ముందు {hours} గంటలు ఏమీ తినకండి. నీళ్లు తాగవచ్చు. డాక్టర్ వద్దనకపోతే మామూలు మందులు వేసుకోండి.', MED)
    k('labCart', 'Your tests', 'आपके टेस्ट', 'మీ పరీక్షలు')
    k('labCartEmpty', 'No tests selected', 'कोई टेस्ट नहीं चुना', 'పరీక్షలు ఎంచుకోలేదు')
    k('browseTests', 'Browse tests', 'टेस्ट देखें', 'పరీక్షలు చూడండి')
    k('sampleCollectionAddress', 'Sample collection address', 'सैंपल लेने का पता', 'శాంపిల్ సేకరణ చిరునామా')
    k('sampleCollectionTime', 'Collection time', 'सैंपल का समय', 'సేకరణ సమయం')
    k('youSaveVsMrp', 'You save {amount} on MRP', 'MRP पर {amount} की बचत', 'MRP పై {amount} ఆదా')
    k('labOrderTitle', 'Lab test order', 'लैब टेस्ट ऑर्डर', 'ల్యాబ్ పరీక్ష ఆర్డర్')
    k('labBooked', 'Sample collection booked', 'सैंपल कलेक्शन बुक हुआ', 'శాంపిల్ సేకరణ బుక్ అయింది')
    k('trackOrder', 'Track order', 'ऑर्डर ट्रैक करें', 'ఆర్డర్ ట్రాక్ చేయండి')
    k('myLabOrders', 'My lab orders', 'मेरे लैब ऑर्डर', 'నా ల్యాబ్ ఆర్డర్లు')
    k('noLabOrders', 'No lab orders yet', 'अभी कोई लैब ऑर्डर नहीं', 'ఇంకా ల్యాబ్ ఆర్డర్లు లేవు')
    k('labPendingPayment', 'Payment pending', 'भुगतान बाकी', 'చెల్లింపు పెండింగ్')
    k('labScheduled', 'Collection scheduled', 'कलेक्शन तय', 'సేకరణ షెడ్యూల్ అయింది')
    k('labSampleCollected', 'Sample collected', 'सैंपल लिया गया', 'శాంపిల్ సేకరించారు')
    k('labProcessing', 'Processing at lab', 'लैब में जाँच जारी', 'ల్యాబ్‌లో ప్రాసెసింగ్')
    k('labReportReady', 'Report ready', 'रिपोर्ट तैयार', 'నివేదిక సిద్ధం')
    k('labCancelled', 'Cancelled', 'रद्द', 'రద్దు చేయబడింది')
    k('labPartner', 'Lab partner', 'लैब पार्टनर', 'ల్యాబ్ భాగస్వామి')
    k('viewReport', 'View report', 'रिपोर्ट देखें', 'నివేదిక చూడండి')
    k('labReport', 'Lab report', 'लैब रिपोर्ट', 'ల్యాబ్ నివేదిక', MED)
    k('trackSampleCollection', 'Track sample collection', 'सैंपल कलेक्शन ट्रैक करें', 'శాంపిల్ సేకరణ ట్రాక్ చేయండి')
    k('orderStatus', 'Order status', 'ऑर्डर की स्थिति', 'ఆర్డర్ స్థితి')
    k('cancelOrder', 'Cancel order', 'ऑर्डर रद्द करें', 'ఆర్డర్ రద్దు చేయండి')
    k('labOrderCancelled', 'Order cancelled. Any payment will be refunded.', 'ऑर्डर रद्द हुआ। भुगतान वापस किया जाएगा।', 'ఆర్డర్ రద్దయింది. చెల్లింపు తిరిగి ఇవ్వబడుతుంది.')
    k('labReportNote', 'Your doctor will be able to see the report. Discuss the results with them.', 'आपके डॉक्टर रिपोर्ट देख सकेंगे। परिणामों पर उनसे बात करें।', 'మీ డాక్టర్ నివేదికను చూడగలరు. ఫలితాల గురించి వారితో మాట్లాడండి.')
    k('cancelReasonTitle', 'Why are you cancelling?', 'आप क्यों रद्द कर रहे हैं?', 'ఎందుకు రద్దు చేస్తున్నారు?')

    # ------------------------------------------------------------ §49 Second opinion
    k('secondOpinion', 'Second opinion', 'दूसरी राय', 'రెండో అభిప్రాయం', MED)
    k('secondOpinionIntro', 'Share your reports with a senior specialist and get a written opinion.', 'अपनी रिपोर्ट वरिष्ठ विशेषज्ञ से साझा करें और लिखित राय पाएँ।', 'మీ నివేదికలను సీనియర్ నిపుణుడితో పంచుకుని లిఖిత అభిప్రాయం పొందండి.', MED)
    k('requestSecondOpinion', 'Request a second opinion', 'दूसरी राय का अनुरोध करें', 'రెండో అభిప్రాయం కోరండి', MED)
    k('myRequests', 'My requests', 'मेरे अनुरोध', 'నా అభ్యర్థనలు')
    k('noSecondOpinions', 'No requests yet', 'अभी कोई अनुरोध नहीं', 'ఇంకా అభ్యర్థనలు లేవు')
    k('secondOpinionUnavailable', 'Second opinions are not available right now', 'दूसरी राय अभी उपलब्ध नहीं है', 'రెండో అభిప్రాయం ప్రస్తుతం అందుబాటులో లేదు')
    k('chooseSpecialty', 'Choose a specialty', 'विशेषज्ञता चुनें', 'నిపుణత ఎంచుకోండి')
    k('opinionWithinHours', 'Written opinion within {hours} hours', '{hours} घंटे में लिखित राय', '{hours} గంటల్లో లిఖిత అభిప్రాయం')
    k('yourQuestion', 'Your question', 'आपका सवाल', 'మీ ప్రశ్న')
    k('yourQuestionHint', 'What would you like the specialist to review? Include your main concern and current treatment.', 'विशेषज्ञ से क्या देखवाना चाहते हैं? मुख्य चिंता और मौजूदा इलाज लिखें।', 'నిపుణుడు ఏమి పరిశీలించాలి? మీ ప్రధాన సమస్య, ప్రస్తుత చికిత్స రాయండి.')
    k('questionTooShort', 'Please write at least {count} characters', 'कम से कम {count} अक्षर लिखें', 'కనీసం {count} అక్షరాలు రాయండి')
    k('recordsToShare', 'Records to share', 'साझा करने के रिकॉर्ड', 'పంచుకునే రికార్డులు')
    k('noRecordsToShare', 'No records yet. You can still ask your question.', 'अभी कोई रिकॉर्ड नहीं। आप फिर भी सवाल पूछ सकते हैं।', 'ఇంకా రికార్డులు లేవు. అయినా ప్రశ్న అడగవచ్చు.')
    k('secondOpinionConsent', 'I agree to share my question and the {count} selected records, read-only, with the specialist who takes up this request. Access is logged.', 'मैं अपना सवाल और चुने गए {count} रिकॉर्ड, केवल पढ़ने के लिए, इस अनुरोध को लेने वाले विशेषज्ञ से साझा करने की सहमति देता/देती हूँ। पहुँच दर्ज की जाती है।', 'నా ప్రశ్నను, ఎంచుకున్న {count} రికార్డులను ఈ అభ్యర్థనను స్వీకరించే నిపుణుడితో (చదవడానికి మాత్రమే) పంచుకోవడానికి అంగీకరిస్తున్నాను. యాక్సెస్ నమోదవుతుంది.')
    k('secondOpinionDisclaimer', 'A second opinion is advice based on the records shared. It does not replace an examination. In an emergency call 108.', 'दूसरी राय साझा रिकॉर्ड पर आधारित सलाह है। यह जाँच का विकल्प नहीं है। आपात स्थिति में 108 पर कॉल करें।', 'రెండో అభిప్రాయం పంచుకున్న రికార్డుల ఆధారంగా ఇచ్చే సలహా. ఇది పరీక్షకు ప్రత్యామ్నాయం కాదు. అత్యవసరంలో 108కి కాల్ చేయండి.', MED)
    k('secondOpinionSubmitted', 'Request sent to specialists', 'अनुरोध विशेषज्ञों को भेजा गया', 'అభ్యర్థన నిపుణులకు పంపబడింది')
    k('soPendingPayment', 'Payment pending', 'भुगतान बाकी', 'చెల్లింపు పెండింగ్')
    k('soOpen', 'Waiting for a specialist', 'विशेषज्ञ की प्रतीक्षा', 'నిపుణుడి కోసం వేచి ఉంది')
    k('soClaimed', 'Specialist reviewing', 'विशेषज्ञ देख रहे हैं', 'నిపుణుడు పరిశీలిస్తున్నారు')
    k('soAnswered', 'Opinion ready', 'राय तैयार', 'అభిప్రాయం సిద్ధం')
    k('soCancelled', 'Cancelled', 'रद्द', 'రద్దు చేయబడింది')
    k('specialist', 'Specialist', 'विशेषज्ञ', 'నిపుణుడు')
    k('expectedBy', 'Expected by', 'अपेक्षित समय', 'ఆశించిన సమయం')
    k('recordsShared', 'Records shared', 'साझा किए रिकॉर्ड', 'పంచుకున్న రికార్డులు')
    k('specialistOpinion', "Specialist's opinion", 'विशेषज्ञ की राय', 'నిపుణుడి అభిప్రాయం', MED)
    k('opinionBy', 'By {name}', '{name} द्वारा', '{name} ద్వారా')
    k('recommendations', 'Recommendations', 'सुझाव', 'సిఫార్సులు')
    k('bookTeleconsult', 'Book a video consultation', 'वीडियो परामर्श बुक करें', 'వీడియో సంప్రదింపు బుక్ చేయండి')
    k('opinionPendingBody', 'We will notify you when the specialist has answered.', 'विशेषज्ञ के जवाब देने पर हम आपको सूचित करेंगे।', 'నిపుణుడు జవాబిచ్చినప్పుడు మీకు తెలియజేస్తాం.')

    # ------------------------------------------------------------ §50 ABDM
    k('createAbha', 'Create ABHA', 'ABHA बनाएँ', 'ABHA సృష్టించండి')
    k('createAbhaSub', 'Get your Health ID with a mobile OTP', 'मोबाइल OTP से अपनी हेल्थ आईडी पाएँ', 'మొబైల్ OTP తో మీ హెల్త్ ఐడీ పొందండి')
    k('createAbhaIntro', 'Enter the mobile number to verify. An OTP will be sent to it.', 'सत्यापन के लिए मोबाइल नंबर दर्ज करें। उस पर OTP भेजा जाएगा।', 'ధృవీకరణ కోసం మొబైల్ నంబర్ నమోదు చేయండి. దానికి OTP వస్తుంది.')
    k('linkAbha', 'Link existing ABHA', 'मौजूदा ABHA जोड़ें', 'ఉన్న ABHA లింక్ చేయండి')
    k('linkAbhaSub', 'Already have a 14-digit ABHA number?', 'पहले से 14 अंकों का ABHA नंबर है?', 'ఇప్పటికే 14 అంకెల ABHA నంబర్ ఉందా?')
    k('linkAbhaIntro', 'Enter your ABHA number. An OTP will be sent to the mobile linked with it.', 'अपना ABHA नंबर दर्ज करें। उससे जुड़े मोबाइल पर OTP भेजा जाएगा।', 'మీ ABHA నంబర్ నమోదు చేయండి. దానికి లింక్ అయిన మొబైల్‌కు OTP వస్తుంది.')
    k('abhaMobileLabel', 'Mobile number', 'मोबाइल नंबर', 'మొబైల్ నంబర్')
    k('abhaOtpSent', 'Enter the 6-digit OTP we sent.', 'भेजा गया 6 अंकों का OTP दर्ज करें।', 'పంపిన 6 అంకెల OTP నమోదు చేయండి.')
    k('abhaCreated', 'Your ABHA is ready', 'आपका ABHA तैयार है', 'మీ ABHA సిద్ధంగా ఉంది')
    k('abhaLinked', 'ABHA linked', 'ABHA जुड़ गया', 'ABHA లింక్ అయింది')
    k('abdmPrivacyNote', 'ABHA is issued by the National Health Authority (ABDM). We never share your records without your consent.', 'ABHA राष्ट्रीय स्वास्थ्य प्राधिकरण (ABDM) जारी करता है। आपकी सहमति के बिना हम रिकॉर्ड साझा नहीं करते।', 'ABHA ను జాతీయ ఆరోగ్య ప్రాధికార సంస్థ (ABDM) జారీ చేస్తుంది. మీ సమ్మతి లేకుండా మేము రికార్డులు పంచుకోము.')
    k('fetchRecords', 'Fetch records from other hospitals', 'दूसरे अस्पतालों से रिकॉर्ड मँगाएँ', 'ఇతర ఆసుపత్రుల నుండి రికార్డులు తెప్పించండి')
    k('fetchRecordsSub', 'Via ABDM, with your consent', 'ABDM के माध्यम से, आपकी सहमति से', 'ABDM ద్వారా, మీ సమ్మతితో')
    k('fetchRecordsIntro', 'Ask hospitals linked to your ABHA to share your records. You approve the request in your ABHA app.', 'अपने ABHA से जुड़े अस्पतालों से रिकॉर्ड साझा करने को कहें। अनुरोध आप अपने ABHA ऐप में स्वीकृत करते हैं।', 'మీ ABHA కి లింక్ అయిన ఆసుపత్రులను రికార్డులు పంచుకోమని అడగండి. అభ్యర్థనను మీ ABHA యాప్‌లో ఆమోదిస్తారు.')
    k('recordTypesToFetch', 'Record types', 'रिकॉर्ड के प्रकार', 'రికార్డు రకాలు')
    k('hiPrescription', 'Prescriptions', 'पर्चे', 'ప్రిస్క్రిప్షన్లు', MED)
    k('hiDiagnosticReport', 'Diagnostic reports', 'जाँच रिपोर्ट', 'రోగనిర్ధారణ నివేదికలు', MED)
    k('hiDischargeSummary', 'Discharge summaries', 'डिस्चार्ज सारांश', 'డిశ్చార్జ్ సారాంశాలు', MED)
    k('hiOpConsultation', 'OP consultations', 'ओपीडी परामर्श', 'ఓపీ సంప్రదింపులు', MED)
    k('dateRange', 'Date range', 'तारीख़ सीमा', 'తేదీ పరిధి')
    k('abdmConsentExplain', 'Records are used only for your care (purpose CAREMGT). You can see every request below.', 'रिकॉर्ड केवल आपकी देखभाल (उद्देश्य CAREMGT) के लिए उपयोग होते हैं। हर अनुरोध नीचे दिखता है।', 'రికార్డులు మీ సంరక్షణకు మాత్రమే (ఉద్దేశం CAREMGT) వాడబడతాయి. ప్రతి అభ్యర్థన కింద కనిపిస్తుంది.')
    k('sendConsentRequest', 'Send consent request', 'सहमति अनुरोध भेजें', 'సమ్మతి అభ్యర్థన పంపండి')
    k('abdmRequestSent', 'Request sent. Approve it in your ABHA app.', 'अनुरोध भेजा गया। इसे अपने ABHA ऐप में स्वीकृत करें।', 'అభ్యర్థన పంపబడింది. మీ ABHA యాప్‌లో ఆమోదించండి.')
    k('myConsentRequests', 'My requests', 'मेरे अनुरोध', 'నా అభ్యర్థనలు')
    k('noConsentRequests', 'No requests yet', 'अभी कोई अनुरोध नहीं', 'ఇంకా అభ్యర్థనలు లేవు')
    k('abdmRequested', 'Waiting for approval', 'स्वीकृति की प्रतीक्षा', 'ఆమోదం కోసం వేచి ఉంది')
    k('abdmGranted', 'Approved', 'स्वीकृत', 'ఆమోదించబడింది')
    k('abdmDenied', 'Denied', 'अस्वीकृत', 'తిరస్కరించబడింది')
    k('abdmExpired', 'Expired', 'समाप्त', 'గడువు ముగిసింది')
    k('abdmDataReceived', 'Records received', 'रिकॉर्ड प्राप्त', 'రికార్డులు అందాయి')
    k('recordsImported', '{count} records imported', '{count} रिकॉर्ड आयात हुए', '{count} రికార్డులు దిగుమతి అయ్యాయి')
    k('importedViaAbdm', 'Imported via ABDM', 'ABDM से आयातित', 'ABDM ద్వారా దిగుమతి')

    # ------------------------------------------------------------ §51 Insurance
    k('insurance', 'Insurance', 'बीमा', 'బీమా')
    k('insuranceSub', 'Policies, cashless hospitals, claims', 'पॉलिसी, कैशलेस अस्पताल, क्लेम', 'పాలసీలు, క్యాష్‌లెస్ ఆసుపత్రులు, క్లెయిమ్‌లు')
    k('addPolicy', 'Add policy', 'पॉलिसी जोड़ें', 'పాలసీ జోడించండి')
    k('editPolicy', 'Edit policy', 'पॉलिसी बदलें', 'పాలసీ మార్చండి')
    k('deletePolicy', 'Remove policy', 'पॉलिसी हटाएँ', 'పాలసీ తీసివేయండి')
    k('deletePolicyBody', 'Remove this policy from your profile?', 'इस पॉलिसी को प्रोफ़ाइल से हटाएँ?', 'ఈ పాలసీని ప్రొఫైల్ నుండి తీసివేయాలా?')
    k('noPolicies', 'No insurance policies', 'कोई बीमा पॉलिसी नहीं', 'బీమా పాలసీలు లేవు')
    k('noPoliciesBody', 'Add your health insurance to find cashless hospitals and get renewal reminders.', 'कैशलेस अस्पताल खोजने और नवीनीकरण रिमाइंडर पाने के लिए अपना स्वास्थ्य बीमा जोड़ें।', 'క్యాష్‌లెస్ ఆసుపత్రులు కనుగొనడానికి, రెన్యూవల్ రిమైండర్ల కోసం మీ ఆరోగ్య బీమా జోడించండి.')
    k('expiringSoon', 'Expiring soon', 'जल्द समाप्त', 'త్వరలో గడువు')
    k('sumInsuredValue', 'Cover {amount}', 'कवर {amount}', 'కవర్ {amount}')
    k('findCashlessHospitals', 'Find cashless hospitals', 'कैशलेस अस्पताल खोजें', 'క్యాష్‌లెస్ ఆసుపత్రులు వెతకండి')
    k('cashlessHospitals', 'Cashless hospitals', 'कैशलेस अस्पताल', 'క్యాష్‌లెస్ ఆసుపత్రులు')
    k('noCashlessHospitals', 'No cashless hospitals listed for this insurer', 'इस बीमाकर्ता के लिए कोई कैशलेस अस्पताल सूचीबद्ध नहीं', 'ఈ బీమా సంస్థకు క్యాష్‌లెస్ ఆసుపత్రులు లేవు')
    k('cashlessIntro', 'Hospitals with a cashless tie-up with {insurer}.', '{insurer} के साथ कैशलेस सुविधा वाले अस्पताल।', '{insurer}తో క్యాష్‌లెస్ ఒప్పందం ఉన్న ఆసుపత్రులు.')
    k('cashlessVerifyNote', 'Always confirm cashless eligibility with your insurer or TPA before admission.', 'भर्ती से पहले बीमाकर्ता या TPA से कैशलेस पात्रता की पुष्टि ज़रूर करें।', 'చేరే ముందు బీమా సంస్థ లేదా TPA తో క్యాష్‌లెస్ అర్హతను నిర్ధారించుకోండి.')
    k('claimHelp', 'Claims', 'क्लेम', 'క్లెయిమ్‌లు')
    k('claimChecklist', 'Claim checklist', 'क्लेम चेकलिस्ट', 'క్లెయిమ్ చెక్‌లిస్ట్')
    k('claimChecklistSub', 'Steps and documents for cashless and reimbursement', 'कैशलेस और रीइम्बर्समेंट के चरण और दस्तावेज़', 'క్యాష్‌లెస్, రీయింబర్స్‌మెంట్ దశలు, పత్రాలు')
    k('cashless', 'Cashless', 'कैशलेस', 'క్యాష్‌లెస్')
    k('reimbursement', 'Reimbursement', 'रीइम्बर्समेंट', 'రీయింబర్స్‌మెంట్')
    k('claimSteps', 'Steps', 'चरण', 'దశలు')
    k('insurer', 'Insurer', 'बीमाकर्ता', 'బీమా సంస్థ')
    k('policyNumber', 'Policy number', 'पॉलिसी नंबर', 'పాలసీ నంబర్')
    k('policyNumberKeep', 'Saved: {masked}. Leave empty to keep it.', 'सहेजा: {masked}। रखने के लिए खाली छोड़ें।', 'సేవ్ అయింది: {masked}. అలాగే ఉంచాలంటే ఖాళీగా వదలండి.')
    k('planNameOptional', 'Plan name (optional)', 'प्लान का नाम (वैकल्पिक)', 'ప్లాన్ పేరు (ఐచ్ఛికం)')
    k('policyType', 'Policy type', 'पॉलिसी प्रकार', 'పాలసీ రకం')
    k('policyIndividual', 'Individual', 'व्यक्तिगत', 'వ్యక్తిగత')
    k('policyFamilyFloater', 'Family floater', 'फ़ैमिली फ़्लोटर', 'ఫ్యామిలీ ఫ్లోటర్')
    k('policyCorporate', 'Corporate', 'कॉरपोरेट', 'కార్పొరేట్')
    k('policyGovernment', 'Government scheme', 'सरकारी योजना', 'ప్రభుత్వ పథకం')
    k('sumInsuredOptional', 'Sum insured (optional)', 'बीमा राशि (वैकल्पिक)', 'బీమా మొత్తం (ఐచ్ఛికం)')
    k('validFrom', 'Valid from', 'से मान्य', 'నుండి చెల్లుతుంది')
    k('validTo', 'Valid to', 'तक मान्य', 'వరకు చెల్లుతుంది')
    k('tpaOptional', 'TPA name (optional)', 'TPA का नाम (वैकल्पिक)', 'TPA పేరు (ఐచ్ఛికం)')
    k('uploadCardPhoto', 'Add insurance card photo', 'बीमा कार्ड की फ़ोटो जोड़ें', 'బీమా కార్డు ఫోటో జోడించండి')
    k('cardPhotoAdded', 'Card photo added', 'कार्ड फ़ोटो जुड़ गई', 'కార్డు ఫోటో జోడించబడింది')
    k('insuranceCardTitle', 'Insurance card', 'बीमा कार्ड', 'బీమా కార్డు')
    k('policyDatesInvalid', 'Choose valid from and valid to dates (end after start)', 'मान्य तिथियाँ चुनें (अंत, शुरुआत के बाद)', 'చెల్లుబాటు తేదీలు ఎంచుకోండి (ముగింపు ప్రారంభం తర్వాత)')
    k('policyPrivacyNote', 'Policy numbers are stored encrypted and shown masked.', 'पॉलिसी नंबर एन्क्रिप्ट करके रखे जाते हैं और छिपाकर दिखाए जाते हैं।', 'పాలసీ నంబర్లు ఎన్‌క్రిప్ట్ చేసి నిల్వ చేయబడతాయి, మాస్క్ చేసి చూపబడతాయి.')

    # ------------------------------------------------------------ §52 Preventive
    k('preventiveCare', 'Preventive care', 'निवारक देखभाल', 'నివారణ సంరక్షణ', MED)
    k('pvOverdue', 'Overdue', 'समय बीत गया', 'గడువు దాటింది')
    k('pvDue', 'Due now', 'अभी करवाएँ', 'ఇప్పుడు చేయించాలి')
    k('pvUpcoming', 'Upcoming', 'आगामी', 'రాబోయేవి')
    k('pvDone', 'Done', 'हो गया', 'పూర్తయింది')
    k('pvNotApplicable', 'Not applicable', 'लागू नहीं', 'వర్తించదు')
    k('noPreventiveItems', 'Nothing scheduled', 'कुछ निर्धारित नहीं', 'ఏమీ షెడ్యూల్ కాలేదు')
    k('markAsDone', 'Mark as done', 'पूरा चिह्नित करें', 'పూర్తయినట్లు గుర్తించండి')
    k('markedDone', 'Marked as done', 'पूरा चिह्नित किया', 'పూర్తయినట్లు గుర్తించబడింది')
    k('whenWasItDone', 'When was "{name}" done?', '"{name}" कब किया गया?', '"{name}" ఎప్పుడు చేశారు?')
    k('lastDoneOn', 'Last done {date}', 'पिछली बार {date}', 'చివరిసారి {date}')
    k('repeatsEveryMonths', 'Repeats every {months} months', 'हर {months} महीने में', 'ప్రతి {months} నెలలకు')
    k('preventiveNote', 'Based on age and sex. Your doctor may advise a different schedule.', 'आयु और लिंग पर आधारित। आपके डॉक्टर अलग समय-सारिणी सुझा सकते हैं।', 'వయస్సు, లింగం ఆధారంగా. మీ డాక్టర్ వేరే షెడ్యూల్ సూచించవచ్చు.', MED)
    k('preventiveNoteFixture', 'A sample schedule based on age and sex, pending clinical review. Please confirm with your doctor.', 'आयु और लिंग पर आधारित नमूना समय-सारिणी, चिकित्सकीय समीक्षा बाकी। कृपया डॉक्टर से पुष्टि करें।', 'వయస్సు, లింగం ఆధారంగా నమూనా షెడ్యూల్, వైద్య సమీక్ష పెండింగ్. దయచేసి డాక్టర్‌తో నిర్ధారించుకోండి.', MED)

    # ------------------------------------------------------------ §53 Exercise
    k('exercisePlan', 'Exercise plan', 'व्यायाम योजना', 'వ్యాయామ ప్లాన్')
    k('noExercisePlan', 'No exercise plan yet', 'अभी कोई व्यायाम योजना नहीं', 'ఇంకా వ్యాయామ ప్లాన్ లేదు')
    k('noExercisePlanBody', 'A doctor or physiotherapist can create one for you.', 'डॉक्टर या फ़िज़ियोथेरेपिस्ट आपके लिए योजना बना सकते हैं।', 'డాక్టర్ లేదా ఫిజియోథెరపిస్ట్ మీ కోసం ప్లాన్ తయారు చేయగలరు.')
    k('bookPhysioVisit', 'Book a physiotherapy home visit', 'फ़िज़ियोथेरेपी होम विज़िट बुक करें', 'ఫిజియోథెరపీ ఇంటి సందర్శన బుక్ చేయండి')
    k('bookPhysioVisitSub', 'A physiotherapist visits your home', 'फ़िज़ियोथेरेपिस्ट आपके घर आएँगे', 'ఫిజియోథెరపిస్ట్ మీ ఇంటికి వస్తారు')
    k('todaysExercises', "Today's exercises", 'आज के व्यायाम', 'ఈరోజు వ్యాయామాలు')
    k('setsReps', '{sets} sets × {reps} reps', '{sets} सेट × {reps} बार', '{sets} సెట్లు × {reps} సార్లు')
    k('holdSeconds', 'Hold {seconds} s', '{seconds} सेकंड रोकें', '{seconds} సె. పట్టి ఉంచండి')
    k('startTimer', 'Start timer', 'टाइमर शुरू करें', 'టైమర్ ప్రారంభించండి')
    k('precautions', 'Precautions', 'सावधानियाँ', 'జాగ్రత్తలు')
    k('markExerciseDone', 'Mark {name} as done', '{name} पूरा चिह्नित करें', '{name} పూర్తయినట్లు గుర్తించండి')
    k('finishSession', 'Finish session ({done}/{total})', 'सत्र पूरा करें ({done}/{total})', 'సెషన్ ముగించండి ({done}/{total})')
    k('sessionsDone', '{done} of {planned} sessions done', '{planned} में से {done} सत्र पूरे', '{planned}లో {done} సెషన్లు పూర్తి')
    k('painTrend', 'Pain after sessions', 'सत्र के बाद दर्द', 'సెషన్ల తర్వాత నొప్పి', MED)
    k('painTrendSemantic', 'Pain score trend, latest {score} out of 10', 'दर्द स्कोर रुझान, नवीनतम 10 में से {score}', 'నొప్పి స్కోర్ ధోరణి, తాజా 10కి {score}', MED)
    k('howIsYourPain', 'How is your pain now?', 'अब दर्द कैसा है?', 'ఇప్పుడు నొప్పి ఎలా ఉంది?', MED)
    k('painScoreValue', 'Pain {score} / 10', 'दर्द {score} / 10', 'నొప్పి {score} / 10', MED)
    k('noPain', 'No pain', 'कोई दर्द नहीं', 'నొప్పి లేదు', MED)
    k('worstPain', 'Worst pain', 'सबसे तेज़ दर्द', 'అత్యధిక నొప్పి', MED)
    k('highPainNote', 'High pain: your therapist will be told. Stop exercising and rest.', 'तेज़ दर्द: आपके थेरेपिस्ट को बताया जाएगा। व्यायाम रोकें और आराम करें।', 'ఎక్కువ నొప్పి: మీ థెరపిస్ట్‌కు తెలియజేస్తాం. వ్యాయామం ఆపి విశ్రాంతి తీసుకోండి.', MED)
    k('sessionSaved', 'Session saved. Well done!', 'सत्र सहेजा गया। शाबाश!', 'సెషన్ సేవ్ అయింది. బాగా చేశారు!')
    k('sessionSavedHighPain', 'Session saved. Your therapist has been told about the pain.', 'सत्र सहेजा गया। थेरेपिस्ट को दर्द के बारे में बताया गया।', 'సెషన్ సేవ్ అయింది. నొప్పి గురించి థెరపిస్ట్‌కు తెలియజేశాం.')
    k('exerciseSafetyNote', 'Stop if you feel sharp pain, dizziness or breathlessness. Call 108 in an emergency.', 'तेज़ दर्द, चक्कर या साँस फूलने पर रुकें। आपात स्थिति में 108 पर कॉल करें।', 'తీవ్రమైన నొప్పి, తలతిరుగుడు లేదా ఆయాసం అనిపిస్తే ఆపండి. అత్యవసరంలో 108కి కాల్ చేయండి.', MED)

    # ------------------------------------------------------------ §54 Diet
    k('dietPlan', 'Diet plan', 'आहार योजना', 'ఆహార ప్రణాళిక')
    k('noDietPlan', 'No diet plan yet', 'अभी कोई आहार योजना नहीं', 'ఇంకా ఆహార ప్రణాళిక లేదు')
    k('noDietPlanBody', 'A doctor or dietitian can create one for you.', 'डॉक्टर या डायटीशियन आपके लिए बना सकते हैं।', 'డాక్టర్ లేదా డైటీషియన్ మీ కోసం తయారు చేయగలరు.')
    k('calorieTarget', 'Target {kcal} kcal a day', 'रोज़ {kcal} kcal लक्ष्य', 'రోజుకు {kcal} kcal లక్ష్యం')
    k('adherence14d', 'Followed (14 days)', 'पालन (14 दिन)', 'పాటించినవి (14 రోజులు)')
    k('dietAdherenceSemantic', 'Diet followed {pct} percent over 14 days', '14 दिनों में {pct} प्रतिशत आहार का पालन', '14 రోజుల్లో {pct} శాతం ఆహారం పాటించారు')
    k('todaysMeals', "Today's meals", 'आज का भोजन', 'ఈరోజు భోజనం')
    k('followed', 'Followed', 'पालन किया', 'పాటించాను')
    k('notFollowed', 'Not followed', 'पालन नहीं किया', 'పాటించలేదు')
    k('foodsToAvoid', 'Foods to avoid', 'इनसे बचें', 'తినకూడనివి')
    k('slotEarlyMorning', 'Early morning', 'सुबह जल्दी', 'తెల్లవారుజాము')
    k('slotBreakfast', 'Breakfast', 'नाश्ता', 'అల్పాహారం')
    k('slotMidMorning', 'Mid-morning', 'दोपहर से पहले', 'మధ్యాహ్నానికి ముందు')
    k('slotLunch', 'Lunch', 'दोपहर का भोजन', 'మధ్యాహ్న భోజనం')
    k('slotEvening', 'Evening snack', 'शाम का नाश्ता', 'సాయంత్రం అల్పాహారం')
    k('slotDinner', 'Dinner', 'रात का भोजन', 'రాత్రి భోజనం')
    k('slotBedtime', 'Bedtime', 'सोने से पहले', 'పడుకునే ముందు')
    k('dietDisclaimer', 'Follow your doctor or dietitian if their advice differs. Tell them about any new symptoms.', 'डॉक्टर या डायटीशियन की सलाह अलग हो तो उसे मानें। नए लक्षण हों तो उन्हें बताएँ।', 'డాక్టర్ లేదా డైటీషియన్ సలహా వేరుగా ఉంటే దాన్ని పాటించండి. కొత్త లక్షణాలు ఉంటే వారికి చెప్పండి.', MED)

    # ------------------------------------------------------------ §55 Ambulance
    k('bookPrivateAmbulance', 'Book private ambulance', 'निजी एम्बुलेंस बुक करें', 'ప్రైవేట్ అంబులెన్స్ బుక్ చేయండి')
    k('bookPrivateAmbulanceSub', 'Track the vehicle live. Call 108 first in an emergency.', 'गाड़ी लाइव ट्रैक करें। आपात स्थिति में पहले 108 पर कॉल करें।', 'వాహనాన్ని లైవ్‌గా ట్రాక్ చేయండి. అత్యవసరంలో ముందు 108కి కాల్ చేయండి.')
    k('privateAmbulance', 'Private ambulance', 'निजी एम्बुलेंस', 'ప్రైవేట్ అంబులెన్స్')
    k('call108First', 'Life-threatening emergency? Call 108 first. A private ambulance does not replace 108.', 'जानलेवा आपात स्थिति? पहले 108 पर कॉल करें। निजी एम्बुलेंस 108 का विकल्प नहीं है।', 'ప్రాణాపాయ అత్యవసరమా? ముందు 108కి కాల్ చేయండి. ప్రైవేట్ అంబులెన్స్ 108కి ప్రత్యామ్నాయం కాదు.')
    k('ambulanceType', 'Ambulance type', 'एम्बुलेंस का प्रकार', 'అంబులెన్స్ రకం')
    k('ambBls', 'Basic (BLS)', 'बेसिक (BLS)', 'బేసిక్ (BLS)', MED)
    k('ambAls', 'Advanced (ALS)', 'एडवांस्ड (ALS)', 'అడ్వాన్స్‌డ్ (ALS)', MED)
    k('ambBlsDesc', 'Oxygen, stretcher and trained staff. For stable patients.', 'ऑक्सीजन, स्ट्रेचर और प्रशिक्षित स्टाफ़। स्थिर मरीज़ों के लिए।', 'ఆక్సిజన్, స్ట్రెచర్, శిక్షణ పొందిన సిబ్బంది. స్థిరంగా ఉన్న రోగులకు.', MED)
    k('ambAlsDesc', 'Cardiac monitor, advanced life support and a paramedic. For serious conditions.', 'कार्डियक मॉनिटर, एडवांस्ड लाइफ़ सपोर्ट और पैरामेडिक। गंभीर स्थिति के लिए।', 'కార్డియాక్ మానిటర్, అధునాతన ప్రాణ సహాయం, పారామెడిక్. తీవ్ర పరిస్థితులకు.', MED)
    k('pickupLocation', 'Pickup location', 'पिकअप स्थान', 'పికప్ ప్రదేశం')
    k('locating', 'Finding your location…', 'आपका स्थान खोज रहे हैं…', 'మీ ప్రదేశం కనుగొంటున్నాం…')
    k('gpsLocation', 'GPS {lat}, {lng}', 'GPS {lat}, {lng}', 'GPS {lat}, {lng}')
    k('currentLocation', 'Current location', 'वर्तमान स्थान', 'ప్రస్తుత ప్రదేశం')
    k('pickupAddressHint', 'House, street, landmark (helps the driver)', 'मकान, गली, लैंडमार्क (ड्राइवर की मदद के लिए)', 'ఇల్లు, వీధి, ల్యాండ్‌మార్క్ (డ్రైవర్‌కు సహాయం)')
    k('destinationHospital', 'Destination hospital', 'गंतव्य अस्पताल', 'గమ్య ఆసుపత్రి')
    k('destinationOptional', 'Hospital (optional)', 'अस्पताल (वैकल्पिक)', 'ఆసుపత్రి (ఐచ్ఛికం)')
    k('nearestSuitable', 'Nearest suitable hospital', 'निकटतम उपयुक्त अस्पताल', 'సమీపంలోని తగిన ఆసుపత్రి')
    k('requestAmbulance', 'Request ambulance', 'एम्बुलेंस मँगाएँ', 'అంబులెన్స్ కోరండి')
    k('ambulanceDefaultReason', 'Transport to hospital', 'अस्पताल ले जाना', 'ఆసుపత్రికి తరలింపు')
    k('ambulanceNote', 'Charges depend on the partner and distance. The care team is alerted too.', 'शुल्क पार्टनर और दूरी पर निर्भर है। केयर टीम को भी सूचित किया जाता है।', 'ఛార్జీలు భాగస్వామి, దూరంపై ఆధారపడతాయి. కేర్ టీమ్‌కు కూడా తెలియజేస్తాం.')
    k('ambulanceTracking', 'Ambulance', 'एम्बुलेंस', 'అంబులెన్స్')
    k('ambSearching', 'Finding an ambulance', 'एम्बुलेंस खोज रहे हैं', 'అంబులెన్స్ వెతుకుతున్నాం')
    k('ambAssigned', 'Ambulance assigned', 'एम्बुलेंस तय हुई', 'అంబులెన్స్ కేటాయించబడింది')
    k('ambEnRoute', 'On the way', 'रास्ते में', 'దారిలో ఉంది')
    k('ambArrived', 'Arrived', 'पहुँच गई', 'చేరుకుంది')
    k('ambTransporting', 'Going to hospital', 'अस्पताल जा रही है', 'ఆసుపత్రికి వెళ్తోంది')
    k('ambCompleted', 'Reached hospital', 'अस्पताल पहुँची', 'ఆసుపత్రికి చేరింది')
    k('ambCancelled', 'Cancelled', 'रद्द', 'రద్దు చేయబడింది')
    k('ambNoVehicle', 'No vehicle available', 'कोई गाड़ी उपलब्ध नहीं', 'వాహనం అందుబాటులో లేదు')
    k('noVehicleBody', 'No private ambulance is available nearby. Call 108 now.', 'पास में कोई निजी एम्बुलेंस उपलब्ध नहीं। अभी 108 पर कॉल करें।', 'సమీపంలో ప్రైవేట్ అంబులెన్స్ లేదు. ఇప్పుడే 108కి కాల్ చేయండి.')
    k('vehicle', 'Vehicle', 'गाड़ी', 'వాహనం')
    k('driver', 'Driver', 'ड्राइवर', 'డ్రైవర్')
    k('openInMaps', 'Open in Maps', 'मैप में खोलें', 'మ్యాప్స్‌లో తెరవండి')
    k('openStreetMap', 'OpenStreetMap', 'OpenStreetMap', 'OpenStreetMap')
    k('locationUpdatedAt', 'Location updated {time}', 'स्थान {time} पर अपडेट हुआ', 'ప్రదేశం {time}కి అప్‌డేట్ అయింది')
    k('statusTimeline', 'Status', 'स्थिति', 'స్థితి')
    k('cancelAmbulance', 'Cancel ambulance', 'एम्बुलेंस रद्द करें', 'అంబులెన్స్ రద్దు చేయండి')
    k('cancelAmbulanceBody', 'Cancel only if help is no longer needed.', 'केवल तभी रद्द करें जब मदद की ज़रूरत न हो।', 'సహాయం అవసరం లేనప్పుడు మాత్రమే రద్దు చేయండి.')
    k('cancelledByUser', 'Cancelled by the family', 'परिवार द्वारा रद्द', 'కుటుంబం రద్దు చేసింది')

    # ------------------------------------------------------------ §56 Safety
    k('safetyLocation', 'Safety & location', 'सुरक्षा और स्थान', 'భద్రత & ప్రదేశం')
    k('safetyLocationSub', 'Safe zone, companion mode, SOS button', 'सुरक्षित क्षेत्र, साथी मोड, SOS बटन', 'సురక్షిత ప్రాంతం, సహచర మోడ్, SOS బటన్')
    k('safetyIntro', 'For people who may wander or get confused, such as with memory problems.', 'उनके लिए जो भटक सकते हैं या भ्रमित हो सकते हैं, जैसे याददाश्त की समस्या में।', 'దారి తప్పే లేదా గందరగోళపడే వారి కోసం, ఉదా. జ్ఞాపకశక్తి సమస్యలు ఉన్నవారు.')
    k('safeZone', 'Safe zone', 'सुरक्षित क्षेत्र', 'సురక్షిత ప్రాంతం')
    k('safeZoneSub', "Get an alert if {name} leaves the area", '{name} क्षेत्र से बाहर जाएँ तो सूचना पाएँ', '{name} ప్రాంతం దాటితే హెచ్చరిక పొందండి')
    k('safeZoneSelfSub', 'Set up by family with care permission', 'देखभाल अनुमति वाले परिवारजन सेट करते हैं', 'సంరక్షణ అనుమతి ఉన్న కుటుంబం ఏర్పాటు చేస్తుంది')
    k('safeZoneIntro', 'If {name} leaves this area while companion mode is on, family get an alert with a map link.', 'साथी मोड चालू रहते {name} इस क्षेत्र से बाहर जाएँ तो परिवार को मैप लिंक के साथ सूचना मिलती है।', 'సహచర మోడ్ ఆన్‌లో ఉన్నప్పుడు {name} ఈ ప్రాంతం దాటితే కుటుంబానికి మ్యాప్ లింక్‌తో హెచ్చరిక వస్తుంది.')
    k('safeZoneAlerts', 'Safe zone alerts', 'सुरक्षित क्षेत्र सूचनाएँ', 'సురక్షిత ప్రాంత హెచ్చరికలు')
    k('safeZoneAlertsSub', 'Alert family when outside the zone', 'क्षेत्र से बाहर होने पर परिवार को सूचित करें', 'ప్రాంతం దాటితే కుటుంబానికి తెలియజేయండి')
    k('zoneCentre', 'Centre (home)', 'केंद्र (घर)', 'కేంద్రం (ఇల్లు)')
    k('useCurrentLocation', 'Use current location', 'वर्तमान स्थान उपयोग करें', 'ప్రస్తుత ప్రదేశం వాడండి')
    k('zoneLabelHint', 'Label (e.g. Home)', 'लेबल (जैसे घर)', 'లేబుల్ (ఉదా. ఇల్లు)')
    k('radius', 'Radius', 'दायरा', 'వ్యాసార్థం')
    k('metersValue', '{meters} m', '{meters} मी', '{meters} మీ')
    k('activeHoursOnly', 'Only during set hours', 'केवल तय घंटों में', 'నిర్ణీత గంటల్లో మాత్రమే')
    k('alwaysActive', 'Always active', 'हमेशा सक्रिय', 'ఎల్లప్పుడూ సక్రియం')
    k('safeZoneNeedsCenter', 'Set the centre first (use current location)', 'पहले केंद्र सेट करें (वर्तमान स्थान)', 'ముందు కేంద్రం సెట్ చేయండి (ప్రస్తుత ప్రదేశం)')
    k('safeZoneRadiusInvalid', 'Radius must be between 100 m and 5 km', 'दायरा 100 मी से 5 किमी के बीच होना चाहिए', 'వ్యాసార్థం 100 మీ నుండి 5 కి.మీ మధ్య ఉండాలి')
    k('safeZonePrivacy', 'Only the latest location is kept; there is no location history.', 'केवल नवीनतम स्थान रखा जाता है; स्थान का इतिहास नहीं रखा जाता।', 'తాజా ప్రదేశం మాత్రమే ఉంచబడుతుంది; ప్రదేశ చరిత్ర ఉండదు.')
    k('lastKnownLocation', 'Last known location', 'अंतिम ज्ञात स्थान', 'చివరిగా తెలిసిన ప్రదేశం')
    k('noLocationYet', 'No location shared yet. Turn on companion mode on their phone.', 'अभी कोई स्थान साझा नहीं। उनके फ़ोन पर साथी मोड चालू करें।', 'ఇంకా ప్రదేశం పంచుకోలేదు. వారి ఫోన్‌లో సహచర మోడ్ ఆన్ చేయండి.')
    k('insideSafeZone', 'Inside the safe zone', 'सुरक्षित क्षेत्र के अंदर', 'సురక్షిత ప్రాంతంలో ఉన్నారు')
    k('outsideSafeZone', 'Outside the safe zone', 'सुरक्षित क्षेत्र के बाहर', 'సురక్షిత ప్రాంతం బయట ఉన్నారు')
    k('companionMode', 'Companion mode', 'साथी मोड', 'సహచర మోడ్')
    k('companionModeSub', 'Share this phone\'s location with family', 'इस फ़ोन का स्थान परिवार से साझा करें', 'ఈ ఫోన్ ప్రదేశాన్ని కుటుంబంతో పంచుకోండి')
    k('companionIntro', 'While CareCompanion is open, this phone shares its location every 5 minutes so family can check you are safe.', 'केयरकम्पैनियन खुला रहने पर यह फ़ोन हर 5 मिनट में स्थान साझा करता है ताकि परिवार जान सके कि आप सुरक्षित हैं।', 'కేర్‌కంపానియన్ తెరిచి ఉన్నప్పుడు ఈ ఫోన్ ప్రతి 5 నిమిషాలకు ప్రదేశాన్ని పంచుకుంటుంది, మీరు సురక్షితంగా ఉన్నారని కుటుంబం చూడవచ్చు.')
    k('companionOn', 'On: sharing location while the app is open', 'चालू: ऐप खुला रहने पर स्थान साझा हो रहा है', 'ఆన్: యాప్ తెరిచి ఉన్నప్పుడు ప్రదేశం పంచుకుంటోంది')
    k('companionOff', 'Off', 'बंद', 'ఆఫ్')
    k('companionOwnDevice', 'Companion mode is turned on from the phone of the person being cared for.', 'साथी मोड उसी व्यक्ति के फ़ोन से चालू होता है जिसकी देखभाल हो रही है।', 'సంరక్షణ పొందే వ్యక్తి ఫోన్ నుండే సహచర మోడ్ ఆన్ చేయాలి.')
    k('companionForegroundOnly', 'Works only while the app is open on screen; it does not track in the background.', 'केवल ऐप स्क्रीन पर खुला होने पर काम करता है; बैकग्राउंड में ट्रैक नहीं करता।', 'యాప్ స్క్రీన్‌పై తెరిచి ఉన్నప్పుడే పనిచేస్తుంది; బ్యాక్‌గ్రౌండ్‌లో ట్రాక్ చేయదు.')
    k('withdrawConsent', 'Withdraw consent', 'सहमति वापस लें', 'సమ్మతి ఉపసంహరించండి')
    k('companionConsentTitle', 'Share your location?', 'अपना स्थान साझा करें?', 'మీ ప్రదేశాన్ని పంచుకోవాలా?')
    k('companionConsent1', 'Your location is sent every 5 minutes while the app is open.', 'ऐप खुला रहने पर हर 5 मिनट में आपका स्थान भेजा जाता है।', 'యాప్ తెరిచి ఉన్నప్పుడు ప్రతి 5 నిమిషాలకు మీ ప్రదేశం పంపబడుతుంది.')
    k('companionConsent2', 'Family with alert permission and your care coordinator can see your latest location.', 'सूचना अनुमति वाले परिवारजन और केयर कोऑर्डिनेटर आपका नवीनतम स्थान देख सकते हैं।', 'హెచ్చరిక అనుమతి ఉన్న కుటుంబం, కేర్ కోఆర్డినేటర్ మీ తాజా ప్రదేశాన్ని చూడగలరు.')
    k('companionConsent3', 'Only the latest location is stored. No history is kept.', 'केवल नवीनतम स्थान रखा जाता है। कोई इतिहास नहीं।', 'తాజా ప్రదేశం మాత్రమే నిల్వ ఉంటుంది. చరిత్ర ఉంచబడదు.')
    k('companionConsent4', 'You can turn it off or withdraw consent at any time.', 'आप इसे कभी भी बंद कर सकते हैं या सहमति वापस ले सकते हैं।', 'మీరు ఎప్పుడైనా ఆఫ్ చేయవచ్చు లేదా సమ్మతి ఉపసంహరించవచ్చు.')
    k('companionConsentAgree', 'I understand and agree to share my location', 'मैं समझता/समझती हूँ और स्थान साझा करने की सहमति देता/देती हूँ', 'నాకు అర్థమైంది, ప్రదేశం పంచుకోవడానికి అంగీకరిస్తున్నాను')
    k('agreeAndTurnOn', 'Agree and turn on', 'सहमत हूँ और चालू करें', 'అంగీకరించి ఆన్ చేయండి')
    k('sosButtonPairing', 'SOS button', 'SOS बटन', 'SOS బటన్')
    k('sosButtonPairingSub', 'Pair a wearable emergency button', 'पहनने योग्य आपात बटन जोड़ें', 'ధరించే అత్యవసర బటన్ జత చేయండి')
    k('sosButtonIntro', 'Pressing a paired SOS button alerts emergency contacts, the same as SOS in the app.', 'जुड़ा SOS बटन दबाने पर ऐप के SOS की तरह आपात संपर्कों को सूचना जाती है।', 'జత చేసిన SOS బటన్ నొక్కితే యాప్‌లోని SOS లాగే అత్యవసర సంపర్కాలకు హెచ్చరిక వెళ్తుంది.')
    k('deviceId', 'Device ID', 'डिवाइस आईडी', 'డివైస్ ఐడీ')
    k('deviceIdHelp', 'Printed on the back of the button or its box', 'बटन के पीछे या डिब्बे पर छपा', 'బటన్ వెనుక లేదా డబ్బాపై ముద్రించి ఉంటుంది')
    k('deviceModelOptional', 'Model (optional)', 'मॉडल (वैकल्पिक)', 'మోడల్ (ఐచ్ఛికం)')
    k('pairDevice', 'Pair button', 'बटन जोड़ें', 'బటన్ జత చేయండి')
    k('pairedDevices', 'Paired on this phone', 'इस फ़ोन पर जुड़े', 'ఈ ఫోన్‌లో జత చేసినవి')
    k('noPairedDevices', 'No buttons paired from this phone', 'इस फ़ोन से कोई बटन नहीं जुड़ा', 'ఈ ఫోన్ నుండి బటన్‌లు జత చేయలేదు')
    k('sosButtonPaired', 'SOS button paired', 'SOS बटन जुड़ गया', 'SOS బటన్ జత అయింది')
    k('unpair', 'Unpair', 'हटाएँ', 'జత తొలగించండి')
    k('sosButtonNote', 'A supportive device, not a replacement for 108.', 'एक सहायक उपकरण, 108 का विकल्प नहीं।', 'సహాయక పరికరం, 108కి ప్రత్యామ్నాయం కాదు.')

    # ------------------------------------------------------------ §57 Company plan
    k('haveCompanyCode', 'Have a company code?', 'कंपनी कोड है?', 'కంపెనీ కోడ్ ఉందా?')
    k('companyCodeHelp', 'If your employer sponsors CareCompanion, enter the code they gave you.', 'यदि आपका नियोक्ता केयरकम्पैनियन प्रायोजित करता है, तो दिया गया कोड दर्ज करें।', 'మీ యజమాని కేర్‌కంపానియన్‌ను స్పాన్సర్ చేస్తే, వారు ఇచ్చిన కోడ్ నమోదు చేయండి.')
    k('companyCode', 'Company code', 'कंपनी कोड', 'కంపెనీ కోడ్')
    k('companyCodeInvalid', 'Enter the full code', 'पूरा कोड दर्ज करें', 'పూర్తి కోడ్ నమోదు చేయండి')
    k('companyPlanActivated', 'Plan activated, sponsored by {name}', 'योजना सक्रिय, {name} द्वारा प्रायोजित', 'ప్లాన్ సక్రియం, {name} స్పాన్సర్ చేశారు')
    k('sponsoredBy', 'Sponsored by {name}', '{name} द्वारा प्रायोजित', '{name} స్పాన్సర్ చేశారు')

    # ------------------------------------------------------------ §60 Offers / wallet / invites
    k('offersAndWallet', 'Offers & wallet', 'ऑफ़र और वॉलेट', 'ఆఫర్లు & వాలెట్')
    k('couponCode', 'Coupon code', 'कूपन कोड', 'కూపన్ కోడ్')
    k('couponApplied', '{code} applied', '{code} लागू हुआ', '{code} వర్తించింది')
    k('couponDiscount', 'Coupon discount', 'कूपन छूट', 'కూపన్ తగ్గింపు')
    k('useWalletBalance', 'Use wallet balance', 'वॉलेट बैलेंस उपयोग करें', 'వాలెట్ బ్యాలెన్స్ వాడండి')
    k('walletAvailable', '{amount} available', '{amount} उपलब्ध', '{amount} అందుబాటులో')
    k('walletUsedLabel', 'Wallet', 'वॉलेट', 'వాలెట్')
    k('payableAmount', 'To pay', 'भुगतान करना है', 'చెల్లించాల్సింది')
    k('fullyCoveredNote', 'Fully covered: no payment needed.', 'पूरी तरह कवर: भुगतान की ज़रूरत नहीं।', 'పూర్తిగా కవర్: చెల్లింపు అవసరం లేదు.')
    k('checkoutSummarySemantic', 'Subtotal {subtotal}, discount {discount}, wallet {wallet}, to pay {payable}', 'उप-योग {subtotal}, छूट {discount}, वॉलेट {wallet}, देय {payable}', 'ఉపమొత్తం {subtotal}, తగ్గింపు {discount}, వాలెట్ {wallet}, చెల్లించాల్సింది {payable}')
    k('wallet', 'Wallet', 'वॉलेट', 'వాలెట్')
    k('walletSub', 'Balance and rewards', 'बैलेंस और रिवॉर्ड', 'బ్యాలెన్స్, రివార్డులు')
    k('walletBalance', 'Wallet balance', 'वॉलेट बैलेंस', 'వాలెట్ బ్యాలెన్స్')
    k('walletBalanceSemantic', 'Wallet balance {amount}', 'वॉलेट बैलेंस {amount}', 'వాలెట్ బ్యాలెన్స్ {amount}')
    k('walletNote', 'Wallet credit can be used on bookings. It cannot be withdrawn and expires after 365 days.', 'वॉलेट क्रेडिट बुकिंग पर उपयोग होता है। इसे निकाला नहीं जा सकता और 365 दिन बाद समाप्त हो जाता है।', 'వాలెట్ క్రెడిట్‌ను బుకింగ్‌లకు వాడవచ్చు. విత్‌డ్రా చేయలేరు, 365 రోజుల తర్వాత గడువు ముగుస్తుంది.')
    k('transactions', 'Transactions', 'लेन-देन', 'లావాదేవీలు')
    k('noTransactions', 'No transactions yet', 'अभी कोई लेन-देन नहीं', 'ఇంకా లావాదేవీలు లేవు')
    k('inviteFamilyFriends', 'Invite family & friends', 'परिवार और दोस्तों को आमंत्रित करें', 'కుటుంబం & స్నేహితులను ఆహ్వానించండి')
    k('inviteRewardSub', 'You both get wallet credit after their first paid service', 'उनकी पहली सशुल्क सेवा के बाद दोनों को वॉलेट क्रेडिट', 'వారి మొదటి చెల్లింపు సేవ తర్వాత ఇద్దరికీ వాలెట్ క్రెడిట్')
    k('inviteIntro', 'Share your code. When they complete their first paid service, you both get wallet credit.', 'अपना कोड साझा करें। उनकी पहली सशुल्क सेवा पूरी होने पर दोनों को वॉलेट क्रेडिट मिलेगा।', 'మీ కోడ్ పంచుకోండి. వారి మొదటి చెల్లింపు సేవ పూర్తయ్యాక ఇద్దరికీ వాలెట్ క్రెడిట్ వస్తుంది.')
    k('yourInviteCode', 'Your invite code', 'आपका आमंत्रण कोड', 'మీ ఆహ్వాన కోడ్')
    k('shareInvite', 'Share invite', 'आमंत्रण साझा करें', 'ఆహ్వానం పంచుకోండి')
    k('friendsInvited', 'Joined with your code', 'आपके कोड से जुड़े', 'మీ కోడ్‌తో చేరినవారు')
    k('rewardsEarned', 'Rewards earned', 'कमाए रिवॉर्ड', 'పొందిన రివార్డులు')
    k('haveInviteCode', 'Have an invite code?', 'आमंत्रण कोड है?', 'ఆహ్వాన కోడ్ ఉందా?')
    k('inviteCode', 'Invite code', 'आमंत्रण कोड', 'ఆహ్వాన కోడ్')
    k('inviteCodeInvalid', 'That code does not look right', 'यह कोड सही नहीं लगता', 'ఈ కోడ్ సరిగా లేదు')
    k('inviteRedeemed', 'Invite code applied. Your reward arrives after your first paid service.', 'आमंत्रण कोड लागू हुआ। पहली सशुल्क सेवा के बाद रिवॉर्ड मिलेगा।', 'ఆహ్వాన కోడ్ వర్తించింది. మొదటి చెల్లింపు సేవ తర్వాత రివార్డ్ వస్తుంది.')
    k('inviteTerms', 'Codes can be used once, within 7 days of signing up.', 'कोड साइन अप के 7 दिनों के अंदर एक बार उपयोग हो सकता है।', 'సైన్ అప్ అయిన 7 రోజుల్లో ఒకసారి మాత్రమే కోడ్ వాడవచ్చు.')
    k('onboardingInviteBody', 'Were you invited by family or a friend? Enter their code to get a welcome reward. You can skip this.', 'क्या परिवार या दोस्त ने आमंत्रित किया? स्वागत रिवॉर्ड के लिए उनका कोड दर्ज करें। आप इसे छोड़ सकते हैं।', 'కుటుంబం లేదా స్నేహితులు ఆహ్వానించారా? స్వాగత రివార్డ్ కోసం వారి కోడ్ నమోదు చేయండి. దీన్ని దాటవేయవచ్చు.')
    k('purposeLabOrder', 'Lab test', 'लैब टेस्ट', 'ల్యాబ్ పరీక్ష')
    k('purposeSecondOpinion', 'Second opinion', 'दूसरी राय', 'రెండో అభిప్రాయం')
    k('purposeAmbulance', 'Ambulance', 'एम्बुलेंस', 'అంబులెన్స్')

    # ------------------------------------------------------------ §61 Support
    k('myTickets', 'My tickets', 'मेरे टिकट', 'నా టికెట్లు')
    k('myTicketsSub', 'Questions about bookings, payments or the app', 'बुकिंग, भुगतान या ऐप के बारे में सवाल', 'బుకింగ్‌లు, చెల్లింపులు లేదా యాప్ గురించి ప్రశ్నలు')
    k('newTicket', 'New ticket', 'नया टिकट', 'కొత్త టికెట్')
    k('noTickets', 'No tickets', 'कोई टिकट नहीं', 'టికెట్లు లేవు')
    k('noTicketsBody', 'Raise a ticket and our support team will reply here.', 'टिकट बनाएँ, हमारी सपोर्ट टीम यहाँ जवाब देगी।', 'టికెట్ సృష్టించండి, మా సపోర్ట్ టీమ్ ఇక్కడ జవాబిస్తుంది.')
    k('ticketCategory', 'What is it about?', 'यह किस बारे में है?', 'ఇది దేని గురించి?')
    k('tcBooking', 'Booking', 'बुकिंग', 'బుకింగ్')
    k('tcPayment', 'Payment', 'भुगतान', 'చెల్లింపు')
    k('tcRefund', 'Refund', 'रिफ़ंड', 'రీఫండ్')
    k('tcAppIssue', 'App issue', 'ऐप समस्या', 'యాప్ సమస్య')
    k('tcClinicalConcern', 'Health concern', 'स्वास्थ्य चिंता', 'ఆరోగ్య సమస్య')
    k('tcOther', 'Other', 'अन्य', 'ఇతర')
    k('clinicalConcernTitle', 'Our care team will review this', 'हमारी केयर टीम इसे देखेगी', 'మా కేర్ టీమ్ దీన్ని పరిశీలిస్తుంది')
    k('clinicalConcernBody', 'Health concerns go to a clinician, not only to support. If it is urgent or someone is very unwell, call 108 now.', 'स्वास्थ्य चिंताएँ केवल सपोर्ट को नहीं, चिकित्सक को भी जाती हैं। तुरंत ज़रूरत हो या कोई बहुत बीमार हो तो अभी 108 पर कॉल करें।', 'ఆరోగ్య సమస్యలు సపోర్ట్‌కే కాదు, వైద్యుడికి వెళ్తాయి. అత్యవసరం లేదా ఎవరైనా చాలా అస్వస్థంగా ఉంటే ఇప్పుడే 108కి కాల్ చేయండి.')
    k('describeIssue', 'Describe the issue', 'समस्या बताएँ', 'సమస్యను వివరించండి')
    k('linkBooking', 'Link a booking (optional)', 'बुकिंग जोड़ें (वैकल्पिक)', 'బుకింగ్ లింక్ చేయండి (ఐచ్ఛికం)')
    k('noBookingsToLink', 'No recent bookings', 'कोई हाल की बुकिंग नहीं', 'ఇటీవలి బుకింగ్‌లు లేవు')
    k('submitTicket', 'Submit', 'जमा करें', 'సమర్పించండి')
    k('ticketCreated', 'Ticket {number} created', 'टिकट {number} बना', 'టికెట్ {number} సృష్టించబడింది')
    k('supportNotForEmergencies', 'Support is not for emergencies. Call 108 in an emergency.', 'सपोर्ट आपात स्थिति के लिए नहीं है। आपात स्थिति में 108 पर कॉल करें।', 'సపోర్ట్ అత్యవసరాల కోసం కాదు. అత్యవసరంలో 108కి కాల్ చేయండి.')
    k('supportTicket', 'Support ticket', 'सपोर्ट टिकट', 'సపోర్ట్ టికెట్')
    k('tsOpen', 'Open', 'खुला', 'తెరిచి ఉంది')
    k('tsPendingCustomer', 'Waiting for you', 'आपकी प्रतीक्षा', 'మీ కోసం వేచి ఉంది')
    k('tsResolved', 'Resolved', 'हल हो गया', 'పరిష్కరించబడింది')
    k('tsClosed', 'Closed', 'बंद', 'మూసివేయబడింది')
    k('handledBy', 'Handled by {name}', '{name} देख रहे हैं', '{name} చూస్తున్నారు')
    k('rateSupport', 'Rate our support', 'हमारी सपोर्ट को रेट करें', 'మా సపోర్ట్‌కు రేటింగ్ ఇవ్వండి')
    k('youRated', 'You rated {score} / 5. Thank you!', 'आपने {score} / 5 रेटिंग दी। धन्यवाद!', 'మీరు {score} / 5 ఇచ్చారు. ధన్యవాదాలు!')
